$axure.loadCurrentPage({
  "url":"project__manager_view_.html",
  "generationDate":new Date(1439391546749.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"14050c14c0884f73b7ebc4e8e4b75718",
    "type":"Axure:Page",
    "name":"Project (manager view)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6017e158ae3f426c875e97d1014e7004",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"674164c4b45c44c0a28f76093d0eb0d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":910,
              "height":900},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e698d0fe99474394bd2a078ad9fedbe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":910,
                  "height":900},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project__manager_view_/u5.png"}},
{
          "id":"a4c399d545fa4d689ea207f5022fd3b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":70},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"302aa6b14fde4092b174009c1f67d77c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":70},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project__manager_view_/u7.png"}},
{
          "id":"dfe03d591b0946ecbaf9b603827356d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":70},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c9128ddd864e30b9a4a71bac2fa042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":70},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63c5de869c0b4f8aa5a534e5ce4e8f16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":138},
            "size":{
              "width":201,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ff9b10f21b64ae68bce3f6ec545c6f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":138},
                "size":{
                  "width":201,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3ef49f836cd41e2a3aedc767829cfe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":169},
            "size":{
              "width":460,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a33d765a42b44978b98b0a246fe014ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":169},
                "size":{
                  "width":460,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"937bb20ebc074350ad25d572a0065f79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":104},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42b5ae342192453a948bd61bd35c25ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":104},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"831aa63046b24e69b3f64af48c1bc8a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":78},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec37536682a449982306a39dfca9780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":78},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u172.png"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u195.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u197.png"}}]}}},
  "objectPaths":{
    "6017e158ae3f426c875e97d1014e7004":{
      "scriptId":"u0",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u1"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u2"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u3"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u4"}},
    "674164c4b45c44c0a28f76093d0eb0d1":{
      "scriptId":"u5"},
    "e698d0fe99474394bd2a078ad9fedbe3":{
      "scriptId":"u6"},
    "a4c399d545fa4d689ea207f5022fd3b2":{
      "scriptId":"u7"},
    "302aa6b14fde4092b174009c1f67d77c":{
      "scriptId":"u8"},
    "dfe03d591b0946ecbaf9b603827356d3":{
      "scriptId":"u9"},
    "27c9128ddd864e30b9a4a71bac2fa042":{
      "scriptId":"u10"},
    "63c5de869c0b4f8aa5a534e5ce4e8f16":{
      "scriptId":"u11"},
    "1ff9b10f21b64ae68bce3f6ec545c6f1":{
      "scriptId":"u12"},
    "f3ef49f836cd41e2a3aedc767829cfe0":{
      "scriptId":"u13"},
    "a33d765a42b44978b98b0a246fe014ac":{
      "scriptId":"u14"},
    "937bb20ebc074350ad25d572a0065f79":{
      "scriptId":"u15"},
    "42b5ae342192453a948bd61bd35c25ba":{
      "scriptId":"u16"},
    "831aa63046b24e69b3f64af48c1bc8a1":{
      "scriptId":"u17"},
    "0ec37536682a449982306a39dfca9780":{
      "scriptId":"u18"}}});