$axure.loadCurrentPage({
  "url":"employee__manager_view_.html",
  "generationDate":new Date(1439391547507.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"02f4798f300d4543beecf9301bf9e444",
    "type":"Axure:Page",
    "name":"Employee (manager view)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9cb848a5df904beb8a6c0c8860433cf1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"6b4bc3f73df24cbda12d4f350dec887f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d13c2508869342febb92430faaa0f084"},
{
          "id":"85f73a063f41490096b374adda69197d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1100,
              "height":1080},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1393349e9e648da9ef04856b4c74de7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1100,
                  "height":1080},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/manager_profile/u5.png"}},
{
          "id":"25e72e0f18de4d38adabb6722bc0917f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":70},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae1a929284764f5c8d224befb5e53c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":70},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project__manager_view_/u7.png"}},
{
          "id":"a51c125bbd0c4b508be7ef2dc74efa02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":70},
            "size":{
              "width":93,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3be6a9f916a146e5b8970abf25ce64bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":70},
                "size":{
                  "width":93,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"175127a3130c43ecb96ae2a301409845",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":146},
            "size":{
              "width":152,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68bc3c9a44c54a989d5a030ff80d8392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":146},
                "size":{
                  "width":152,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4728652e42e4492ad923fbf95bddae7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":243},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41ac8785ce2a480d969a9607d6a8b1dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":243},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee808935aa33471d84bd988d1a0574f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":213},
            "size":{
              "width":98,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78e54e2ab46148a49c0d8a2c0e02faf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":213},
                "size":{
                  "width":98,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"939cde40d23e4ef4badcfd9132315b18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":271},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeb57f9c65fa46108d8221d981c72fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":271},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4818a7eba54447b2a131e84f6a730ad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":484},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68f441cbd0914cdc868d5dc58d3cfcd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":484},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2107b44acca4afca8dba019ca7c9237",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":518},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa180469c1374134b4123663a92b7a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":518},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u21.png"}},
{
          "id":"bb840272344f454283ab436515b17239",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":525},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c4b9f12dc624bcf83dda90c07dee13c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":525},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"285b5ea7bb1f4ced90f16e0ba8313ec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":556},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ba46228ca1f49ccac6a8ab2dd3cfc9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":556},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a175f5b7451b40c19385c2a1023cf9e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":590},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d01c3d3a80df4d959c5dab36ee7705d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":590},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"159598a974a543aa9efa499e9382aae5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":327,
              "y":146},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"919aa9048e3e4412a1b178e5dfa26ae6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":327,
                  "y":146},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a315d885d9eb42159fee50d9bbc4feb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":174},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"694270539b424cb0a6393863061e2755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":174},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c252bf65ae16413791c7459e6cd89a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":269,
              "y":174},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f31f2e943a74185a31cc2e080c44e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":269,
                  "y":174},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90b7cb76f2c446e1be3f4d724df3e573",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":297},
            "size":{
              "width":128,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef7eda19486c468f8566057bc7143a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":297},
                "size":{
                  "width":128,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e475f9c845e347309154fa14689b728e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":19,
              "y":190},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2998324cb90249469c5c34708c837bd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":19,
                  "y":190},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dad55d586a0040358343e4c16736639f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":700},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea50e2199144b7da858e91f8fc06ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":700},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u21.png"}},
{
          "id":"e29ffa14c7834c638dcdc9e4ee913cba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":707},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6f025758a74a06b8529e0bf2527496",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":707},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fe6a1cca5054a96a1bac9d0438cd8fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":738},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd58d44c5c314db793aeb07d8b508da0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":738},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fe89e691f664a2abdc933b278c78f10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":772},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b18596dc68c46dbaa6f6110ba4d78b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":772},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82a87555954c429fab57e4c70fd5352a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":119},
            "size":{
              "width":46,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0781b513b0a9491c91348afb88db1a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":119},
                "size":{
                  "width":46,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb8c232c81a4476ab0d8cc4bad1f09f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":223,
              "y":119},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40052a09425a41818e30cf30cbbb0d38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":223,
                  "y":119},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9509dee7d3f4402bb2b97437e0a34fc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":159,
              "y":95},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8e2960438e24c528779fa0a7f44c8e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":159,
                  "y":95},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3a6ddfdafb747c68209a8c9a8e19069",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":78},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"790911d82e504f18b41ffdca3588d80c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":78},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u172.png"}},
{
          "id":"d4a302176ec14d79a2359357de5e113b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":340},
            "size":{
              "width":570,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7935bdcf5bf5471996d1ee78923272cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":340},
                "size":{
                  "width":570,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/manager_profile/u59.png"}},
{
          "id":"1e1ebc472b46473b818e10f8770c7299",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":910},
            "size":{
              "width":570,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d9e22f13994fd7a3169722549d9ebe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":910},
                "size":{
                  "width":570,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/manager_profile/u61.png"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u195.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u197.png"}}]}},
    "d13c2508869342febb92430faaa0f084":{
      "packageId":"d13c2508869342febb92430faaa0f084",
      "type":"Axure:Master",
      "name":"Manager menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fcaf49c1aa52423e9e9293bb09970ae5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":12.5},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Manager dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"manager_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"4b686096096746da9b953bfc4b8300bc",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":12},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Manager profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"manager_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"d8259fa082bd49d2ae5b97f7bc482501",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":290,
                "y":12},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Statistics in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"statistics.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "9cb848a5df904beb8a6c0c8860433cf1":{
      "scriptId":"u0",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u1"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u2"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u3"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u4"}},
    "6b4bc3f73df24cbda12d4f350dec887f":{
      "scriptId":"u5",
      "fcaf49c1aa52423e9e9293bb09970ae5":{
        "scriptId":"u6"},
      "4b686096096746da9b953bfc4b8300bc":{
        "scriptId":"u7"},
      "d8259fa082bd49d2ae5b97f7bc482501":{
        "scriptId":"u8"}},
    "85f73a063f41490096b374adda69197d":{
      "scriptId":"u9"},
    "c1393349e9e648da9ef04856b4c74de7":{
      "scriptId":"u10"},
    "25e72e0f18de4d38adabb6722bc0917f":{
      "scriptId":"u11"},
    "ae1a929284764f5c8d224befb5e53c58":{
      "scriptId":"u12"},
    "a51c125bbd0c4b508be7ef2dc74efa02":{
      "scriptId":"u13"},
    "3be6a9f916a146e5b8970abf25ce64bd":{
      "scriptId":"u14"},
    "175127a3130c43ecb96ae2a301409845":{
      "scriptId":"u15"},
    "68bc3c9a44c54a989d5a030ff80d8392":{
      "scriptId":"u16"},
    "e4728652e42e4492ad923fbf95bddae7":{
      "scriptId":"u17"},
    "41ac8785ce2a480d969a9607d6a8b1dc":{
      "scriptId":"u18"},
    "ee808935aa33471d84bd988d1a0574f0":{
      "scriptId":"u19"},
    "78e54e2ab46148a49c0d8a2c0e02faf4":{
      "scriptId":"u20"},
    "939cde40d23e4ef4badcfd9132315b18":{
      "scriptId":"u21"},
    "aeb57f9c65fa46108d8221d981c72fad":{
      "scriptId":"u22"},
    "4818a7eba54447b2a131e84f6a730ad1":{
      "scriptId":"u23"},
    "68f441cbd0914cdc868d5dc58d3cfcd6":{
      "scriptId":"u24"},
    "c2107b44acca4afca8dba019ca7c9237":{
      "scriptId":"u25"},
    "aa180469c1374134b4123663a92b7a00":{
      "scriptId":"u26"},
    "bb840272344f454283ab436515b17239":{
      "scriptId":"u27"},
    "9c4b9f12dc624bcf83dda90c07dee13c":{
      "scriptId":"u28"},
    "285b5ea7bb1f4ced90f16e0ba8313ec6":{
      "scriptId":"u29"},
    "4ba46228ca1f49ccac6a8ab2dd3cfc9b":{
      "scriptId":"u30"},
    "a175f5b7451b40c19385c2a1023cf9e6":{
      "scriptId":"u31"},
    "d01c3d3a80df4d959c5dab36ee7705d1":{
      "scriptId":"u32"},
    "159598a974a543aa9efa499e9382aae5":{
      "scriptId":"u33"},
    "919aa9048e3e4412a1b178e5dfa26ae6":{
      "scriptId":"u34"},
    "a315d885d9eb42159fee50d9bbc4feb9":{
      "scriptId":"u35"},
    "694270539b424cb0a6393863061e2755":{
      "scriptId":"u36"},
    "c252bf65ae16413791c7459e6cd89a7f":{
      "scriptId":"u37"},
    "1f31f2e943a74185a31cc2e080c44e28":{
      "scriptId":"u38"},
    "90b7cb76f2c446e1be3f4d724df3e573":{
      "scriptId":"u39"},
    "ef7eda19486c468f8566057bc7143a4a":{
      "scriptId":"u40"},
    "e475f9c845e347309154fa14689b728e":{
      "scriptId":"u41"},
    "2998324cb90249469c5c34708c837bd9":{
      "scriptId":"u42"},
    "dad55d586a0040358343e4c16736639f":{
      "scriptId":"u43"},
    "9ea50e2199144b7da858e91f8fc06ad1":{
      "scriptId":"u44"},
    "e29ffa14c7834c638dcdc9e4ee913cba":{
      "scriptId":"u45"},
    "9d6f025758a74a06b8529e0bf2527496":{
      "scriptId":"u46"},
    "1fe6a1cca5054a96a1bac9d0438cd8fe":{
      "scriptId":"u47"},
    "dd58d44c5c314db793aeb07d8b508da0":{
      "scriptId":"u48"},
    "2fe89e691f664a2abdc933b278c78f10":{
      "scriptId":"u49"},
    "8b18596dc68c46dbaa6f6110ba4d78b5":{
      "scriptId":"u50"},
    "82a87555954c429fab57e4c70fd5352a":{
      "scriptId":"u51"},
    "0781b513b0a9491c91348afb88db1a0f":{
      "scriptId":"u52"},
    "bb8c232c81a4476ab0d8cc4bad1f09f5":{
      "scriptId":"u53"},
    "40052a09425a41818e30cf30cbbb0d38":{
      "scriptId":"u54"},
    "9509dee7d3f4402bb2b97437e0a34fc0":{
      "scriptId":"u55"},
    "e8e2960438e24c528779fa0a7f44c8e9":{
      "scriptId":"u56"},
    "e3a6ddfdafb747c68209a8c9a8e19069":{
      "scriptId":"u57"},
    "790911d82e504f18b41ffdca3588d80c":{
      "scriptId":"u58"},
    "d4a302176ec14d79a2359357de5e113b":{
      "scriptId":"u59"},
    "7935bdcf5bf5471996d1ee78923272cb":{
      "scriptId":"u60"},
    "1e1ebc472b46473b818e10f8770c7299":{
      "scriptId":"u61"},
    "47d9e22f13994fd7a3169722549d9ebe":{
      "scriptId":"u62"}}});