$axure.loadCurrentPage({
  "url":"employee__client_view_.html",
  "generationDate":new Date(1439396099817.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cd5a69e488ee4ecea39e3f8ab2139392",
    "type":"Axure:Page",
    "name":"Employee (client view)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"65aa7dba7c484f07923108b1f1ed73cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1100,
              "height":1280},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c07ed4bb39246d09a8ff55ebd068fd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1100,
                  "height":1280},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee__client_view_/u0.png"}},
{
          "id":"70f27010380a47e1aecb32534bd292e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":70},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2666da89a60e4c7b8139f520b0e21152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":70},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u10.png"}},
{
          "id":"a04f460048454a308c88702e9daea57d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":70},
            "size":{
              "width":93,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bb94de6de474394a667afeb705f5e6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":70},
                "size":{
                  "width":93,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bdb56704f754d1da26066fd6a9fc2cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":146},
            "size":{
              "width":152,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00406fdbe7aa4f8ba8e6095711b7cb96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":146},
                "size":{
                  "width":152,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17e0e56baa3a433d814c43dd02c54a3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":243},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed60e690dd3e4dbe9b9e24a06ff2de0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":243},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfd582e04bae45e995f4d4c126f3b9b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":213},
            "size":{
              "width":98,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a88e6fe3dfe4d4d9d296bdf56edf585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":213},
                "size":{
                  "width":98,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e788ab026974dca818efc78d7d967a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":271},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dd4fbf3c86c4d6db4df4d8ec54d7a59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":271},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d104ee73801c4f63973f5e18d50a07e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":714},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94622d5fad23478aa7abbd97c8567e6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":714},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0baf17a900a475d903bd894e2d2b7c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":748},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dff6bf40b3c4e359db8cf70c59d712c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":748},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"4c88c5040da849e8a05abf65c50acb83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":755},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d524528011d445d86f7f3b1a112ed9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":755},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e1697d6e28845d7873ebe5799059c39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":786},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af3d5ccb4dad4a1db847a197dcc517fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":786},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81ed6c87b51f4b9db3d67ac62da526b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":820},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef007cecbbe4a9b9ccfd8c2f977ff95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":820},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5091f12dedb44eb58b01ff94711396c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":327,
              "y":146},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04cca481baf84296a683784d3e4382b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":327,
                  "y":146},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08a86093f60749e7907ad6092c633306",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":174},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a0bdb3546744e69e072bb5f9c0563d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":174},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c12370c7f2e04ddd9ebef8e085be3eac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":269,
              "y":174},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c9097e870d64587bea03191fb493cff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":269,
                  "y":174},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3f5d56b96254160887eb98f03f6b384",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":297},
            "size":{
              "width":165,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4210856195b64c83b4faec7b9f6b9d24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":297},
                "size":{
                  "width":165,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db95f2bf15f84de4b61327eba47a54b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":19,
              "y":190},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac16ee0aa41d48fcad08175c72338661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":19,
                  "y":190},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cbc927926c34e8094c8ea2fbf8de06d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":930},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8ce05d196ce42e582d20d7a92ab3d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":930},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"40801d86f1de4a6a9142795a3ca6d9e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":937},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"551a367518d640dd85e6f0797c41c32a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":937},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4845b05842a4a679f023b2b987bff0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":968},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67f85ef10ab04a38a82f3c4edbd9136e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":968},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e37303a89de4cf3a62a864f34aa2171",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":1002},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32392a380d1f4fcba84025595d7bd095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":1002},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70c57cba5cb94441824453de23b2ff77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":119},
            "size":{
              "width":46,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"859db69115124bcea364501b03d10324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":119},
                "size":{
                  "width":46,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c9c71f920b24708ae133d0f4cd1a6f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":223,
              "y":119},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84c2d46e7fcd410a934e9717428ff850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":223,
                  "y":119},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3596d267aa994343a7645529bf0da4d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":159,
              "y":95},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c4cc4417e3406dbb6e90ce06cb83d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":159,
                  "y":95},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"356e5e8522b6410aa14c4385d7ee2099",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":78},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e89c2acfc048d694fc07048bc07b2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":78},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"ff043e8811024ff6943d935b93b09121",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":340},
            "size":{
              "width":570,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca40eec44ce14368adcfe8379593c56f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":340},
                "size":{
                  "width":570,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u58.png"}},
{
          "id":"3b2bfd12d8f84829841a6681ab67b915",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":1140},
            "size":{
              "width":570,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49449d42313843c5b796b3e26b9216b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":1140},
                "size":{
                  "width":570,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u60.png"}},
{
          "id":"429fc167c9044e62acd5c39b1c286d34",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"e8947fbd8d314dd8b0d450e383dc9217",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7960479542a744d09a89949d89357fee"},
{
          "id":"af7c1152148243bf8ecd545f6a60be65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":492},
            "size":{
              "width":123,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2558cfc135864332801374e5134ce67c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":492},
                "size":{
                  "width":123,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de0d85006b74410d98e34ad8376b9a2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":526},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8769b62af9cf4c388d045a9fe147a0b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":526},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"b9c8ae1c73194b52a91dbea825c40ebc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":533},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dcddc4f846b4fc091945ec3cb234e27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":533},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e99c89cee18413d826c89f46d3f5209",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":564},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"741710cdfa3848d6bd3f24e8b43ceaf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":564},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03d7af249bd341109a1433e513f55d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":598},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8df947f54f849b98a291a667ffb06f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":598},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u130.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u132.png"}}]}},
    "7960479542a744d09a89949d89357fee":{
      "packageId":"7960479542a744d09a89949d89357fee",
      "type":"Axure:Master",
      "name":"Client menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c1c2bf7a73b142e98889e67c858f6199",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Client dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"client_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"532b2c922e8e4042a2f400488f29927e",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Client profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"client_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "65aa7dba7c484f07923108b1f1ed73cb":{
      "scriptId":"u0"},
    "4c07ed4bb39246d09a8ff55ebd068fd7":{
      "scriptId":"u1"},
    "70f27010380a47e1aecb32534bd292e3":{
      "scriptId":"u2"},
    "2666da89a60e4c7b8139f520b0e21152":{
      "scriptId":"u3"},
    "a04f460048454a308c88702e9daea57d":{
      "scriptId":"u4"},
    "8bb94de6de474394a667afeb705f5e6f":{
      "scriptId":"u5"},
    "8bdb56704f754d1da26066fd6a9fc2cf":{
      "scriptId":"u6"},
    "00406fdbe7aa4f8ba8e6095711b7cb96":{
      "scriptId":"u7"},
    "17e0e56baa3a433d814c43dd02c54a3b":{
      "scriptId":"u8"},
    "ed60e690dd3e4dbe9b9e24a06ff2de0a":{
      "scriptId":"u9"},
    "cfd582e04bae45e995f4d4c126f3b9b5":{
      "scriptId":"u10"},
    "3a88e6fe3dfe4d4d9d296bdf56edf585":{
      "scriptId":"u11"},
    "7e788ab026974dca818efc78d7d967a1":{
      "scriptId":"u12"},
    "9dd4fbf3c86c4d6db4df4d8ec54d7a59":{
      "scriptId":"u13"},
    "d104ee73801c4f63973f5e18d50a07e3":{
      "scriptId":"u14"},
    "94622d5fad23478aa7abbd97c8567e6e":{
      "scriptId":"u15"},
    "a0baf17a900a475d903bd894e2d2b7c1":{
      "scriptId":"u16"},
    "5dff6bf40b3c4e359db8cf70c59d712c":{
      "scriptId":"u17"},
    "4c88c5040da849e8a05abf65c50acb83":{
      "scriptId":"u18"},
    "5d524528011d445d86f7f3b1a112ed9b":{
      "scriptId":"u19"},
    "9e1697d6e28845d7873ebe5799059c39":{
      "scriptId":"u20"},
    "af3d5ccb4dad4a1db847a197dcc517fb":{
      "scriptId":"u21"},
    "81ed6c87b51f4b9db3d67ac62da526b4":{
      "scriptId":"u22"},
    "8ef007cecbbe4a9b9ccfd8c2f977ff95":{
      "scriptId":"u23"},
    "5091f12dedb44eb58b01ff94711396c1":{
      "scriptId":"u24"},
    "04cca481baf84296a683784d3e4382b9":{
      "scriptId":"u25"},
    "08a86093f60749e7907ad6092c633306":{
      "scriptId":"u26"},
    "01a0bdb3546744e69e072bb5f9c0563d":{
      "scriptId":"u27"},
    "c12370c7f2e04ddd9ebef8e085be3eac":{
      "scriptId":"u28"},
    "8c9097e870d64587bea03191fb493cff":{
      "scriptId":"u29"},
    "b3f5d56b96254160887eb98f03f6b384":{
      "scriptId":"u30"},
    "4210856195b64c83b4faec7b9f6b9d24":{
      "scriptId":"u31"},
    "db95f2bf15f84de4b61327eba47a54b9":{
      "scriptId":"u32"},
    "ac16ee0aa41d48fcad08175c72338661":{
      "scriptId":"u33"},
    "6cbc927926c34e8094c8ea2fbf8de06d":{
      "scriptId":"u34"},
    "b8ce05d196ce42e582d20d7a92ab3d5b":{
      "scriptId":"u35"},
    "40801d86f1de4a6a9142795a3ca6d9e8":{
      "scriptId":"u36"},
    "551a367518d640dd85e6f0797c41c32a":{
      "scriptId":"u37"},
    "a4845b05842a4a679f023b2b987bff0a":{
      "scriptId":"u38"},
    "67f85ef10ab04a38a82f3c4edbd9136e":{
      "scriptId":"u39"},
    "0e37303a89de4cf3a62a864f34aa2171":{
      "scriptId":"u40"},
    "32392a380d1f4fcba84025595d7bd095":{
      "scriptId":"u41"},
    "70c57cba5cb94441824453de23b2ff77":{
      "scriptId":"u42"},
    "859db69115124bcea364501b03d10324":{
      "scriptId":"u43"},
    "4c9c71f920b24708ae133d0f4cd1a6f4":{
      "scriptId":"u44"},
    "84c2d46e7fcd410a934e9717428ff850":{
      "scriptId":"u45"},
    "3596d267aa994343a7645529bf0da4d8":{
      "scriptId":"u46"},
    "71c4cc4417e3406dbb6e90ce06cb83d3":{
      "scriptId":"u47"},
    "356e5e8522b6410aa14c4385d7ee2099":{
      "scriptId":"u48"},
    "e5e89c2acfc048d694fc07048bc07b2d":{
      "scriptId":"u49"},
    "ff043e8811024ff6943d935b93b09121":{
      "scriptId":"u50"},
    "ca40eec44ce14368adcfe8379593c56f":{
      "scriptId":"u51"},
    "3b2bfd12d8f84829841a6681ab67b915":{
      "scriptId":"u52"},
    "49449d42313843c5b796b3e26b9216b5":{
      "scriptId":"u53"},
    "429fc167c9044e62acd5c39b1c286d34":{
      "scriptId":"u54",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u55"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u56"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u57"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u58"}},
    "e8947fbd8d314dd8b0d450e383dc9217":{
      "scriptId":"u59",
      "c1c2bf7a73b142e98889e67c858f6199":{
        "scriptId":"u60"},
      "532b2c922e8e4042a2f400488f29927e":{
        "scriptId":"u61"}},
    "af7c1152148243bf8ecd545f6a60be65":{
      "scriptId":"u62"},
    "2558cfc135864332801374e5134ce67c":{
      "scriptId":"u63"},
    "de0d85006b74410d98e34ad8376b9a2e":{
      "scriptId":"u64"},
    "8769b62af9cf4c388d045a9fe147a0b5":{
      "scriptId":"u65"},
    "b9c8ae1c73194b52a91dbea825c40ebc":{
      "scriptId":"u66"},
    "7dcddc4f846b4fc091945ec3cb234e27":{
      "scriptId":"u67"},
    "4e99c89cee18413d826c89f46d3f5209":{
      "scriptId":"u68"},
    "741710cdfa3848d6bd3f24e8b43ceaf3":{
      "scriptId":"u69"},
    "03d7af249bd341109a1433e513f55d3b":{
      "scriptId":"u70"},
    "a8df947f54f849b98a291a667ffb06f9":{
      "scriptId":"u71"}}});