$axure.loadCurrentPage({
  "url":"manager_profile.html",
  "generationDate":new Date(1439394926644.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6523ad17dad44c1ea6511205d8769328",
    "type":"Axure:Page",
    "name":"Manager profile",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"773c42d63e60481aac3b6279f03cd3fe",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"5e6428ecb8314cabbda8b65af423855e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1100,
              "height":1080},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"426c51bfc38a4ff68c7b086ff10b09f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1100,
                  "height":1080},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u8.png"}},
{
          "id":"ee5e81c2e35c4fe5892146b0413d5ec5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":70},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c12ecc20152a4bbf987b8b22c07d8ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":70},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u10.png"}},
{
          "id":"b97e71dd1d4445a78a1cc6d6e4c4c0b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":70},
            "size":{
              "width":93,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"217c2d3e1efd4e65aa0e812a0cc67614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":70},
                "size":{
                  "width":93,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64e705864dd14108850e9b4af04c63b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":146},
            "size":{
              "width":152,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7674b5ed8b884f72b0c1b8e304bd483d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":146},
                "size":{
                  "width":152,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d7a0a5c1205494b839ea7a271065357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":243},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aafb78e2f1b46d0a53a03ce72895372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":243},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"468b0f0e51a343eba75ba2ca92019a93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":213},
            "size":{
              "width":98,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f92b4c587349a484829762c877faa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":213},
                "size":{
                  "width":98,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd41b485156743b9b587cdeeb5bd10d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":271},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f22a6986dc49446db18b73892ced0004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":271},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99271c94b54e48bcb0da66552d65c4e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":484},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"225960ece02645f7b071a0b60af8b522",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":484},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc325b2c593449c08cf5cca87468e58f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":518},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aee37a06146043f8a10dc305a015b395",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":518},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"9ba845517dd4460db2c8e7cb29e613be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":525},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f0b77ee38047fdaf6da850624572d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":525},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4bd53a777604599a7ca886dba1d8c00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":556},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d46644f9d3f46a08a5289eba2b313e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":556},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6c49b8a213a4a10ab95bc68b4915766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":590},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df13c4110d854004bdb2b9bcac4f9b9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":590},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ed64969b0694dec87a3ebfad80b9ec8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":327,
              "y":146},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae4590e63c4642feb2521f7a4ea4b20d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":327,
                  "y":146},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c7703c39313467097a20d3afb05d212",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":174},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e518f4cc95414af5b0a10eb15dcb00f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":174},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17d0c24ad18e4682ba069b7eac3ed871",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":269,
              "y":174},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a366c87ed24e4001a3ba75fb73fef170",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":269,
                  "y":174},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddfa363a4ca341358d4d687bf9bac14e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":297},
            "size":{
              "width":165,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1a082c8bf034bfc918af486f9246fc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":297},
                "size":{
                  "width":165,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e130c568fb954663897592f2bb187a75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":19,
              "y":190},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82f46393b9544f31ac79a33fcadf859f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":19,
                  "y":190},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cae654704cc94246a64346823f540c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":700},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"259686a7ef7a4f549f7e88f6c6e50071",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":700},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"df11a7a81cbe465a83a42ba79b367ef5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":707},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"339e365047d94a6eb0d32873a53aece8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":707},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd4b9e871f0c40fc8b9df19d3caad358",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":738},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49671c2849954c81867b72c4d25195a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":738},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"479aba6c172c48fca38d2b3db30993ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":772},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d66491962c640a59c91d0a211d1bf26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":772},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a68c1aeba7f648729114925e889e13a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":119},
            "size":{
              "width":46,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77e2e1fe155145b88584145f3ce49f5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":119},
                "size":{
                  "width":46,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55f6af2bb27f4141b4fea16ef0275baf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":223,
              "y":119},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c9a9c8111474ac88ed8f981497cac6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":223,
                  "y":119},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f05e1e07bffa46b98c22b5d72d42cc57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":159,
              "y":95},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eea46e87243242008ccbd0c19960b85a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":159,
                  "y":95},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3e40323c92d47d2a750b1b5a295383d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":78},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3298a08b3e0a4c0eacb56b01f556fbd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":78},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"f33651073ef94574ae3be845ea76f48b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d13c2508869342febb92430faaa0f084"},
{
          "id":"7ea7947b0e9b49ba8553cbcab6c21c32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":340},
            "size":{
              "width":570,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afaa8a7bedd14c5b87f222a916afa30c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":340},
                "size":{
                  "width":570,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u58.png"}},
{
          "id":"a65e1b56d05849608821344b32955efe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":910},
            "size":{
              "width":570,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f764dd3d3a564d10a384091af715c0a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":910},
                "size":{
                  "width":570,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u60.png"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u130.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u132.png"}}]}},
    "d13c2508869342febb92430faaa0f084":{
      "packageId":"d13c2508869342febb92430faaa0f084",
      "type":"Axure:Master",
      "name":"Manager menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fcaf49c1aa52423e9e9293bb09970ae5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":12.5},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Manager dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"manager_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"4b686096096746da9b953bfc4b8300bc",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":12},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Manager profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"manager_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"d8259fa082bd49d2ae5b97f7bc482501",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":290,
                "y":12},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Statistics in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"statistics.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "773c42d63e60481aac3b6279f03cd3fe":{
      "scriptId":"u0",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u1"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u2"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u3"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u4"}},
    "5e6428ecb8314cabbda8b65af423855e":{
      "scriptId":"u5"},
    "426c51bfc38a4ff68c7b086ff10b09f7":{
      "scriptId":"u6"},
    "ee5e81c2e35c4fe5892146b0413d5ec5":{
      "scriptId":"u7"},
    "c12ecc20152a4bbf987b8b22c07d8ddc":{
      "scriptId":"u8"},
    "b97e71dd1d4445a78a1cc6d6e4c4c0b2":{
      "scriptId":"u9"},
    "217c2d3e1efd4e65aa0e812a0cc67614":{
      "scriptId":"u10"},
    "64e705864dd14108850e9b4af04c63b5":{
      "scriptId":"u11"},
    "7674b5ed8b884f72b0c1b8e304bd483d":{
      "scriptId":"u12"},
    "8d7a0a5c1205494b839ea7a271065357":{
      "scriptId":"u13"},
    "9aafb78e2f1b46d0a53a03ce72895372":{
      "scriptId":"u14"},
    "468b0f0e51a343eba75ba2ca92019a93":{
      "scriptId":"u15"},
    "b6f92b4c587349a484829762c877faa5":{
      "scriptId":"u16"},
    "cd41b485156743b9b587cdeeb5bd10d4":{
      "scriptId":"u17"},
    "f22a6986dc49446db18b73892ced0004":{
      "scriptId":"u18"},
    "99271c94b54e48bcb0da66552d65c4e4":{
      "scriptId":"u19"},
    "225960ece02645f7b071a0b60af8b522":{
      "scriptId":"u20"},
    "bc325b2c593449c08cf5cca87468e58f":{
      "scriptId":"u21"},
    "aee37a06146043f8a10dc305a015b395":{
      "scriptId":"u22"},
    "9ba845517dd4460db2c8e7cb29e613be":{
      "scriptId":"u23"},
    "65f0b77ee38047fdaf6da850624572d3":{
      "scriptId":"u24"},
    "d4bd53a777604599a7ca886dba1d8c00":{
      "scriptId":"u25"},
    "7d46644f9d3f46a08a5289eba2b313e9":{
      "scriptId":"u26"},
    "b6c49b8a213a4a10ab95bc68b4915766":{
      "scriptId":"u27"},
    "df13c4110d854004bdb2b9bcac4f9b9c":{
      "scriptId":"u28"},
    "4ed64969b0694dec87a3ebfad80b9ec8":{
      "scriptId":"u29"},
    "ae4590e63c4642feb2521f7a4ea4b20d":{
      "scriptId":"u30"},
    "0c7703c39313467097a20d3afb05d212":{
      "scriptId":"u31"},
    "e518f4cc95414af5b0a10eb15dcb00f7":{
      "scriptId":"u32"},
    "17d0c24ad18e4682ba069b7eac3ed871":{
      "scriptId":"u33"},
    "a366c87ed24e4001a3ba75fb73fef170":{
      "scriptId":"u34"},
    "ddfa363a4ca341358d4d687bf9bac14e":{
      "scriptId":"u35"},
    "a1a082c8bf034bfc918af486f9246fc7":{
      "scriptId":"u36"},
    "e130c568fb954663897592f2bb187a75":{
      "scriptId":"u37"},
    "82f46393b9544f31ac79a33fcadf859f":{
      "scriptId":"u38"},
    "cae654704cc94246a64346823f540c26":{
      "scriptId":"u39"},
    "259686a7ef7a4f549f7e88f6c6e50071":{
      "scriptId":"u40"},
    "df11a7a81cbe465a83a42ba79b367ef5":{
      "scriptId":"u41"},
    "339e365047d94a6eb0d32873a53aece8":{
      "scriptId":"u42"},
    "cd4b9e871f0c40fc8b9df19d3caad358":{
      "scriptId":"u43"},
    "49671c2849954c81867b72c4d25195a0":{
      "scriptId":"u44"},
    "479aba6c172c48fca38d2b3db30993ca":{
      "scriptId":"u45"},
    "9d66491962c640a59c91d0a211d1bf26":{
      "scriptId":"u46"},
    "a68c1aeba7f648729114925e889e13a4":{
      "scriptId":"u47"},
    "77e2e1fe155145b88584145f3ce49f5d":{
      "scriptId":"u48"},
    "55f6af2bb27f4141b4fea16ef0275baf":{
      "scriptId":"u49"},
    "1c9a9c8111474ac88ed8f981497cac6a":{
      "scriptId":"u50"},
    "f05e1e07bffa46b98c22b5d72d42cc57":{
      "scriptId":"u51"},
    "eea46e87243242008ccbd0c19960b85a":{
      "scriptId":"u52"},
    "b3e40323c92d47d2a750b1b5a295383d":{
      "scriptId":"u53"},
    "3298a08b3e0a4c0eacb56b01f556fbd2":{
      "scriptId":"u54"},
    "f33651073ef94574ae3be845ea76f48b":{
      "scriptId":"u55",
      "fcaf49c1aa52423e9e9293bb09970ae5":{
        "scriptId":"u56"},
      "4b686096096746da9b953bfc4b8300bc":{
        "scriptId":"u57"},
      "d8259fa082bd49d2ae5b97f7bc482501":{
        "scriptId":"u58"}},
    "7ea7947b0e9b49ba8553cbcab6c21c32":{
      "scriptId":"u59"},
    "afaa8a7bedd14c5b87f222a916afa30c":{
      "scriptId":"u60"},
    "a65e1b56d05849608821344b32955efe":{
      "scriptId":"u61"},
    "f764dd3d3a564d10a384091af715c0a6":{
      "scriptId":"u62"}}});