$axure.loadCurrentPage({
  "url":"project.html",
  "generationDate":new Date(1438957015282.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"05cbaa2a1e9f4d36ab9ec3dfd25adb08",
    "type":"Axure:Page",
    "name":"Project",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6017e158ae3f426c875e97d1014e7004",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"674164c4b45c44c0a28f76093d0eb0d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":51,
              "y":0},
            "size":{
              "width":749,
              "height":900},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e698d0fe99474394bd2a078ad9fedbe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":51,
                  "y":0},
                "size":{
                  "width":749,
                  "height":900},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project/u5.png"}},
{
          "id":"a4c399d545fa4d689ea207f5022fd3b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":20},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"302aa6b14fde4092b174009c1f67d77c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":20},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee/u7.png"}},
{
          "id":"dfe03d591b0946ecbaf9b603827356d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":20},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c9128ddd864e30b9a4a71bac2fa042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":20},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63c5de869c0b4f8aa5a534e5ce4e8f16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":88},
            "size":{
              "width":201,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ff9b10f21b64ae68bce3f6ec545c6f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":88},
                "size":{
                  "width":201,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3ef49f836cd41e2a3aedc767829cfe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":119},
            "size":{
              "width":460,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a33d765a42b44978b98b0a246fe014ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":119},
                "size":{
                  "width":460,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"937bb20ebc074350ad25d572a0065f79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":54},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42b5ae342192453a948bd61bd35c25ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":54},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fa6763d6bf2439faaf9f06bf639839e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":178},
            "size":{
              "width":172,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e164c02a9d1844c288f328f2dfdbe1d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":178},
                "size":{
                  "width":172,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9f035d6da7f44019063581cbee6a135",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":206},
            "size":{
              "width":555,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2ccd6aed5c148c4872361658c1ee0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":206},
                "size":{
                  "width":555,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0de80234d07407391b9416ff9ca64b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":326},
            "size":{
              "width":95,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dc99d9ba59c48d6837344e20b5c2707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":326},
                "size":{
                  "width":95,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f9904e992994b70ab9b891a46499bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":325,
              "y":326},
            "size":{
              "width":440,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e600ad11ac524a228d21036ada693eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":325,
                  "y":326},
                "size":{
                  "width":440,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46eb107dea21411e9109f631649a68fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":496},
            "size":{
              "width":95,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"943f2c8e43d64f2582863df9410ad941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":496},
                "size":{
                  "width":95,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"616dde2db98643b0a99d2200d911f597",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":325,
              "y":496},
            "size":{
              "width":440,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8983db54a1dd416e91a754983584c816",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":325,
                  "y":496},
                "size":{
                  "width":440,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":51,
                "height":900},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":51,
                    "height":900},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}}]}}},
  "objectPaths":{
    "6017e158ae3f426c875e97d1014e7004":{
      "scriptId":"u0",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u1"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u2"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u3"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u4"}},
    "674164c4b45c44c0a28f76093d0eb0d1":{
      "scriptId":"u5"},
    "e698d0fe99474394bd2a078ad9fedbe3":{
      "scriptId":"u6"},
    "a4c399d545fa4d689ea207f5022fd3b2":{
      "scriptId":"u7"},
    "302aa6b14fde4092b174009c1f67d77c":{
      "scriptId":"u8"},
    "dfe03d591b0946ecbaf9b603827356d3":{
      "scriptId":"u9"},
    "27c9128ddd864e30b9a4a71bac2fa042":{
      "scriptId":"u10"},
    "63c5de869c0b4f8aa5a534e5ce4e8f16":{
      "scriptId":"u11"},
    "1ff9b10f21b64ae68bce3f6ec545c6f1":{
      "scriptId":"u12"},
    "f3ef49f836cd41e2a3aedc767829cfe0":{
      "scriptId":"u13"},
    "a33d765a42b44978b98b0a246fe014ac":{
      "scriptId":"u14"},
    "937bb20ebc074350ad25d572a0065f79":{
      "scriptId":"u15"},
    "42b5ae342192453a948bd61bd35c25ba":{
      "scriptId":"u16"},
    "2fa6763d6bf2439faaf9f06bf639839e":{
      "scriptId":"u17"},
    "e164c02a9d1844c288f328f2dfdbe1d3":{
      "scriptId":"u18"},
    "f9f035d6da7f44019063581cbee6a135":{
      "scriptId":"u19"},
    "d2ccd6aed5c148c4872361658c1ee0db":{
      "scriptId":"u20"},
    "f0de80234d07407391b9416ff9ca64b5":{
      "scriptId":"u21"},
    "8dc99d9ba59c48d6837344e20b5c2707":{
      "scriptId":"u22"},
    "6f9904e992994b70ab9b891a46499bd1":{
      "scriptId":"u23"},
    "e600ad11ac524a228d21036ada693eba":{
      "scriptId":"u24"},
    "46eb107dea21411e9109f631649a68fd":{
      "scriptId":"u25"},
    "943f2c8e43d64f2582863df9410ad941":{
      "scriptId":"u26"},
    "616dde2db98643b0a99d2200d911f597":{
      "scriptId":"u27"},
    "8983db54a1dd416e91a754983584c816":{
      "scriptId":"u28"}}});