$axure.loadCurrentPage({
  "url":"employee__employee_view_.html",
  "generationDate":new Date(1439396099507.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c7967b149c2e47d38c27dac2e0e83be1",
    "type":"Axure:Page",
    "name":"Employee (employee view)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a3e32d8be14c4ba683f7f46337e117ff",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"035be0d5f4bb45bcbb72ec170e583374",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c3d56b8804094e519836cba4ec98aa37"},
{
          "id":"32f29bfa65a941a8b7f9bda53041d784",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1100,
              "height":1080},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35389b171e70468e8a6d98fd48eb4f25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1100,
                  "height":1080},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u8.png"}},
{
          "id":"78f93428a94f4268b32f18255aa29a24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":70},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fca4ca6fa6284c09a41d0c1956de321c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":70},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u10.png"}},
{
          "id":"8c8b7fda4a1646959d433d8046fbdbc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":70},
            "size":{
              "width":93,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e326ae2f4a4845802b720e62d5eb0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":70},
                "size":{
                  "width":93,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10caf3ee62e24138a6fde57c1b1c3461",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":146},
            "size":{
              "width":152,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6ee78b3c21c42baa552a7164ba18c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":146},
                "size":{
                  "width":152,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3b1bb1eed964073a50c2b41511dfd3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":243},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"914979b2acb44009b62b9d8239f16367",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":243},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1533fe96fc04e22a1c6ed1bda254eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":213},
            "size":{
              "width":98,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29748e70463547fa8a4c436cd82521cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":213},
                "size":{
                  "width":98,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"815f5be5f40d4a78826b8831405e1ac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":271},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eac90372bb04bd8a8d4c5f00bd924ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":271},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8d0f2a1d921440aa1bbb380825165fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":484},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2a21210a855480488e7ba29eca8696b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":484},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c3287d3ec90432a864006d3bf278a50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":518},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faeb1b7a0eea4b5da3b17b48d606925f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":518},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"e57d6c6e87364648a6191bc877ac8aab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":525},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12b7d3effc664493b6bc93b9f07d71df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":525},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5232577452143009766dc214cf313b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":556},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5471d204c3ce47a8ba4cc6d6c22a461c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":556},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"790bb250b5f7487e953e7fedda392194",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":590},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee8e1c7ce1c8461b9f7bd8b4917e084b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":590},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a99d04e842e4c0c828003d691da0086",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":327,
              "y":146},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6355d4b3fe454d1ea0b815659b7420c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":327,
                  "y":146},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e9f67ec61a84a45b0a9cda9df244856",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":174},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd3d0736df6b4ae39719216af763d07e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":174},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96ddb5fe9f924adfada4d73aac47a9b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":269,
              "y":174},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f481c1950a74a2595f5bb1114a6675e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":269,
                  "y":174},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e19a54dae0814858ad74cda19211f6dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":297},
            "size":{
              "width":165,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53183a2db8764c1da0edf61fa6f1bb5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":297},
                "size":{
                  "width":165,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a113213c3aa543699e3d50ea314851b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":19,
              "y":190},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ebde9b7c4f943efbec0835743875a23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":19,
                  "y":190},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71388fb513934ed28726fbbdbf6f6c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":700},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0abd535d9bec4e508772cac9bfdebfe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":700},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"2d8e959627744bdb86cffbd28988359c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":707},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9182d223f5ff4bcc88604fd8fbf07097",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":707},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98c9d298ee5541cfa2b134f1c2375fd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":738},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac200781f2d345bd87c36cb1f6ca824f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":738},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24e62a40c1c8426285072ab6405f2c71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":772},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2327abb971d4d7fa821a5c29654a641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":772},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d84c04fd9d7c4cec9c16043e479bcc6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":119},
            "size":{
              "width":46,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"227d202f26dd4752baa550f6f0a49c21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":119},
                "size":{
                  "width":46,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfdea323df38477a92131c978a803741",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":223,
              "y":119},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d6858e0826345d09bee779fae789c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":223,
                  "y":119},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"826729b900ff45bc8a2ccbb9cca3bd9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":159,
              "y":95},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d2da39452a48d491b58155810dc0ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":159,
                  "y":95},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71c294ac645442c4989bff70108b3d56",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":78},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1032d9a68ce244fbb461f0f796693ae3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":78},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"32aad9f24586483ebea1ee8e893f042d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":340},
            "size":{
              "width":570,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13cae0fd60e44289b3e9dd6f17568f95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":340},
                "size":{
                  "width":570,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u58.png"}},
{
          "id":"d43125d8c53e46748cca9e9cb39b7959",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":910},
            "size":{
              "width":570,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b16c66fcc4a4d18a8c23ff2b86081e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":910},
                "size":{
                  "width":570,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u60.png"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u130.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u132.png"}}]}},
    "c3d56b8804094e519836cba4ec98aa37":{
      "packageId":"c3d56b8804094e519836cba4ec98aa37",
      "type":"Axure:Master",
      "name":"Employee menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c53b0307d0da4147910ccf3ed931a762",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Employee dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"employee_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"8f5f1397212f454fab65667c4379d05a",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Employee profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"employee_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "a3e32d8be14c4ba683f7f46337e117ff":{
      "scriptId":"u0",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u1"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u2"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u3"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u4"}},
    "035be0d5f4bb45bcbb72ec170e583374":{
      "scriptId":"u5",
      "c53b0307d0da4147910ccf3ed931a762":{
        "scriptId":"u6"},
      "8f5f1397212f454fab65667c4379d05a":{
        "scriptId":"u7"}},
    "32f29bfa65a941a8b7f9bda53041d784":{
      "scriptId":"u8"},
    "35389b171e70468e8a6d98fd48eb4f25":{
      "scriptId":"u9"},
    "78f93428a94f4268b32f18255aa29a24":{
      "scriptId":"u10"},
    "fca4ca6fa6284c09a41d0c1956de321c":{
      "scriptId":"u11"},
    "8c8b7fda4a1646959d433d8046fbdbc6":{
      "scriptId":"u12"},
    "c1e326ae2f4a4845802b720e62d5eb0e":{
      "scriptId":"u13"},
    "10caf3ee62e24138a6fde57c1b1c3461":{
      "scriptId":"u14"},
    "d6ee78b3c21c42baa552a7164ba18c06":{
      "scriptId":"u15"},
    "e3b1bb1eed964073a50c2b41511dfd3f":{
      "scriptId":"u16"},
    "914979b2acb44009b62b9d8239f16367":{
      "scriptId":"u17"},
    "c1533fe96fc04e22a1c6ed1bda254eb1":{
      "scriptId":"u18"},
    "29748e70463547fa8a4c436cd82521cc":{
      "scriptId":"u19"},
    "815f5be5f40d4a78826b8831405e1ac3":{
      "scriptId":"u20"},
    "3eac90372bb04bd8a8d4c5f00bd924ee":{
      "scriptId":"u21"},
    "d8d0f2a1d921440aa1bbb380825165fe":{
      "scriptId":"u22"},
    "c2a21210a855480488e7ba29eca8696b":{
      "scriptId":"u23"},
    "4c3287d3ec90432a864006d3bf278a50":{
      "scriptId":"u24"},
    "faeb1b7a0eea4b5da3b17b48d606925f":{
      "scriptId":"u25"},
    "e57d6c6e87364648a6191bc877ac8aab":{
      "scriptId":"u26"},
    "12b7d3effc664493b6bc93b9f07d71df":{
      "scriptId":"u27"},
    "b5232577452143009766dc214cf313b4":{
      "scriptId":"u28"},
    "5471d204c3ce47a8ba4cc6d6c22a461c":{
      "scriptId":"u29"},
    "790bb250b5f7487e953e7fedda392194":{
      "scriptId":"u30"},
    "ee8e1c7ce1c8461b9f7bd8b4917e084b":{
      "scriptId":"u31"},
    "5a99d04e842e4c0c828003d691da0086":{
      "scriptId":"u32"},
    "6355d4b3fe454d1ea0b815659b7420c8":{
      "scriptId":"u33"},
    "3e9f67ec61a84a45b0a9cda9df244856":{
      "scriptId":"u34"},
    "dd3d0736df6b4ae39719216af763d07e":{
      "scriptId":"u35"},
    "96ddb5fe9f924adfada4d73aac47a9b6":{
      "scriptId":"u36"},
    "7f481c1950a74a2595f5bb1114a6675e":{
      "scriptId":"u37"},
    "e19a54dae0814858ad74cda19211f6dd":{
      "scriptId":"u38"},
    "53183a2db8764c1da0edf61fa6f1bb5b":{
      "scriptId":"u39"},
    "a113213c3aa543699e3d50ea314851b9":{
      "scriptId":"u40"},
    "3ebde9b7c4f943efbec0835743875a23":{
      "scriptId":"u41"},
    "71388fb513934ed28726fbbdbf6f6c17":{
      "scriptId":"u42"},
    "0abd535d9bec4e508772cac9bfdebfe1":{
      "scriptId":"u43"},
    "2d8e959627744bdb86cffbd28988359c":{
      "scriptId":"u44"},
    "9182d223f5ff4bcc88604fd8fbf07097":{
      "scriptId":"u45"},
    "98c9d298ee5541cfa2b134f1c2375fd6":{
      "scriptId":"u46"},
    "ac200781f2d345bd87c36cb1f6ca824f":{
      "scriptId":"u47"},
    "24e62a40c1c8426285072ab6405f2c71":{
      "scriptId":"u48"},
    "f2327abb971d4d7fa821a5c29654a641":{
      "scriptId":"u49"},
    "d84c04fd9d7c4cec9c16043e479bcc6e":{
      "scriptId":"u50"},
    "227d202f26dd4752baa550f6f0a49c21":{
      "scriptId":"u51"},
    "cfdea323df38477a92131c978a803741":{
      "scriptId":"u52"},
    "4d6858e0826345d09bee779fae789c55":{
      "scriptId":"u53"},
    "826729b900ff45bc8a2ccbb9cca3bd9a":{
      "scriptId":"u54"},
    "39d2da39452a48d491b58155810dc0ad":{
      "scriptId":"u55"},
    "71c294ac645442c4989bff70108b3d56":{
      "scriptId":"u56"},
    "1032d9a68ce244fbb461f0f796693ae3":{
      "scriptId":"u57"},
    "32aad9f24586483ebea1ee8e893f042d":{
      "scriptId":"u58"},
    "13cae0fd60e44289b3e9dd6f17568f95":{
      "scriptId":"u59"},
    "d43125d8c53e46748cca9e9cb39b7959":{
      "scriptId":"u60"},
    "4b16c66fcc4a4d18a8c23ff2b86081e1":{
      "scriptId":"u61"}}});