$axure.loadCurrentPage({
  "url":"project_edit__manager_view_.html",
  "generationDate":new Date(1439391547769.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"90719232e879453eaee3c9a719b4857e",
    "type":"Axure:Page",
    "name":"Project edit (manager view)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2959998d85a8443a9de49ec3c8947f26",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"7316e7d3543b48c4ac50440f0731f4f3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d13c2508869342febb92430faaa0f084"},
{
          "id":"11324f8ef4b64c4dbba1dd72472d7c27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1100,
              "height":900},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4ab7bbe06643acb6db7260555d72b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1100,
                  "height":900},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project__manager_view__1/u9.png"}},
{
          "id":"714f641c309240129f34a340f7c8f6c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":70},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605eb43e81674451ab89da658e07eb40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":70},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project__manager_view_/u7.png"}},
{
          "id":"a8c97cd4da7b48cdb9e0d952f67f3d9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":70},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df1b809d5673458c986918c2c98a03be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":70},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2adee0a9aaa4a45a3d89f85e435d3e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":138},
            "size":{
              "width":201,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bae452748624427e94ff42c1ada023cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":138},
                "size":{
                  "width":201,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cfd47893dae4bada72adfe32d324c28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":169},
            "size":{
              "width":460,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"479fed10355340ae95d5168082b5b0c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":169},
                "size":{
                  "width":460,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a16910b6baef4a2aa7f9efefba4652d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":104},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04239b091a434325bf45fd3401cbf8b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":104},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54332f1824f343708803f8e13e983dad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":78},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"873c113c785546f2bcc6a1e54ccc2ed5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":78},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u172.png"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u195.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u197.png"}}]}},
    "d13c2508869342febb92430faaa0f084":{
      "packageId":"d13c2508869342febb92430faaa0f084",
      "type":"Axure:Master",
      "name":"Manager menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fcaf49c1aa52423e9e9293bb09970ae5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":12.5},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Manager dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"manager_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"4b686096096746da9b953bfc4b8300bc",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":12},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Manager profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"manager_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"d8259fa082bd49d2ae5b97f7bc482501",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":290,
                "y":12},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Statistics in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"statistics.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "2959998d85a8443a9de49ec3c8947f26":{
      "scriptId":"u0",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u1"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u2"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u3"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u4"}},
    "7316e7d3543b48c4ac50440f0731f4f3":{
      "scriptId":"u5",
      "fcaf49c1aa52423e9e9293bb09970ae5":{
        "scriptId":"u6"},
      "4b686096096746da9b953bfc4b8300bc":{
        "scriptId":"u7"},
      "d8259fa082bd49d2ae5b97f7bc482501":{
        "scriptId":"u8"}},
    "11324f8ef4b64c4dbba1dd72472d7c27":{
      "scriptId":"u9"},
    "6b4ab7bbe06643acb6db7260555d72b6":{
      "scriptId":"u10"},
    "714f641c309240129f34a340f7c8f6c2":{
      "scriptId":"u11"},
    "605eb43e81674451ab89da658e07eb40":{
      "scriptId":"u12"},
    "a8c97cd4da7b48cdb9e0d952f67f3d9a":{
      "scriptId":"u13"},
    "df1b809d5673458c986918c2c98a03be":{
      "scriptId":"u14"},
    "d2adee0a9aaa4a45a3d89f85e435d3e1":{
      "scriptId":"u15"},
    "bae452748624427e94ff42c1ada023cc":{
      "scriptId":"u16"},
    "4cfd47893dae4bada72adfe32d324c28":{
      "scriptId":"u17"},
    "479fed10355340ae95d5168082b5b0c6":{
      "scriptId":"u18"},
    "a16910b6baef4a2aa7f9efefba4652d7":{
      "scriptId":"u19"},
    "04239b091a434325bf45fd3401cbf8b7":{
      "scriptId":"u20"},
    "54332f1824f343708803f8e13e983dad":{
      "scriptId":"u21"},
    "873c113c785546f2bcc6a1e54ccc2ed5":{
      "scriptId":"u22"}}});