$axure.loadCurrentPage({
  "url":"employee_dashboard.html",
  "generationDate":new Date(1439394925867.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2bb8d80ed1d340b5a2293abbdb184947",
    "type":"Axure:Page",
    "name":"Employee dashboard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e9fac6ca660c49ee81e90cd01031aff1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":110}},
          "adaptiveStyles":{
},
          "masterId":"643f38a9e3bf4284950d1c1c8c2e016e"},
{
          "id":"3432a52f6e864bfdaec6544355732606",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":328}},
          "adaptiveStyles":{
},
          "masterId":"6a4d007a25584617bcd0a52a01713c4b"},
{
          "id":"dc25ed2e0d2040f394152d5b99d53b41",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":213}},
          "adaptiveStyles":{
},
          "masterId":"6a4d007a25584617bcd0a52a01713c4b"},
{
          "id":"f5811b1d9a6c44879f877a1fa830c6e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":477,
              "y":62},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2ea37a2a8c4e1cb2e59097976a29aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":477,
                  "y":62},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u27.png"}},
{
          "id":"6f26d5107ba04f80b126f9422eb557aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":480,
              "y":64},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9200af324d4bec9e6dfec4c6ef6979",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":480,
                  "y":64},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"3d67a0932fb140d1bb4c2373e27e32a9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":94}},
          "adaptiveStyles":{
},
          "masterId":"6a4d007a25584617bcd0a52a01713c4b"},
{
          "id":"3092662f439642b8b63e413aaccafb84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":486,
              "y":64},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df89ef7904b84b488ef1ccaf65b0bcd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":486,
                  "y":64},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"447741136e2e4b1180d79f8ac10d7ab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":493,
              "y":64},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0e743ebcff048b6bff1287cdfcbbf99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":493,
                  "y":64},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"8c2fc04af4804e86a299262be80abe8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":480,
              "y":70},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5519db8e426e475d8454e1fe3f244e1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":480,
                  "y":70},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"2e8f8c34a05e4eaeb2c5bb9f27e73c2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":486,
              "y":70},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"140f29f694574f689b43686e1601b6f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":486,
                  "y":70},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"6e8fca4624524cd39d51ad4622afcd70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":493,
              "y":70},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8621480ae46a47d68c6d211a3455b74c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":493,
                  "y":70},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"91bcab52159c4d53a2e065b7848933b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":480,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcbb205555174e1ea7072d41a20731a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":480,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"5bf2831a0bde4db2824e15d68bee9700",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":486,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"982343d3d58a45d48e67a50d864e0384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":486,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"70445390bff744138de7ed93847a2fc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":493,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25bc81a3bad04f1f9b08c31b3b37e6fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":493,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"fa093eee26964c9bb3e20ea1ba178aa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":516,
              "y":62},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73aa351b81e941d2baf77acbe2aa86b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":516,
                  "y":62},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u27.png"}},
{
          "id":"d31b438aa706476491d9979eb2d47a22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":518,
              "y":65},
            "size":{
              "width":19,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f20b1265267432d8faafe14f5a76e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":518,
                  "y":65},
                "size":{
                  "width":19,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u58.png"}},
{
          "id":"2af21bc5cc5e480abf30f90d82f6a11b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":518,
              "y":71},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8285d957ff8c449b9eef23aa4359a157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":518,
                  "y":71},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u60.png"}},
{
          "id":"62ba98d3faf2443e92493396fdaefeca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":518,
              "y":76},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae349578d98a4c92b8918baf43ec27be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":518,
                  "y":76},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u60.png"}},
{
          "id":"357bf8f95edd46ddbb0290eb68aa322e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":102},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3560c573f8194c029d7a9f49ee71ed92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":102},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56eca7f2e41844e8979961b0b622c148",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":120},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c27c7426e96c4f9c9eccf9b206fcce12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":120},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad102312a55244528a8c35070c586145",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":322,
              "y":60},
            "size":{
              "width":104,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ff574e960cb48d2b5bcd7f1897efe2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":322,
                  "y":60},
                "size":{
                  "width":104,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb7cbf94480e4758b10b21e67c4ad4e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":934,
              "y":64},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a302bf4ca2714d9ab9e327761743a85c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":934,
                  "y":64},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u27.png"}},
{
          "id":"b4ed0b08920447a189691dd48f0841b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":937,
              "y":66},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d29a3b87bada48678596a1833cc04e34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":937,
                  "y":66},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"9cf4addb9ccc4d48a8a17c97e2f7637a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":943,
              "y":66},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c669333d457c438b8be9cc40443414c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":943,
                  "y":66},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"c1b766e0f16541a2b8521ea6f5f34ff9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":950,
              "y":66},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f553d5c3a2244d42826d3472e633f453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":950,
                  "y":66},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"62db7370aeba41ecb67a795c65c2f9c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":937,
              "y":72},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6568e04cb0dd40048559670d36060990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":937,
                  "y":72},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"05ab40e20d9a4074b51d8999341ac27d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":943,
              "y":72},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6721914615ee4bc68107926282abfe6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":943,
                  "y":72},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"d2c9f0cc37de4ce6b73fb73f8864bdb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":950,
              "y":72},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff8167eab1604c98a84db1f61a68cf5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":950,
                  "y":72},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"52c51f7d0f2946b09a182344133480cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":937,
              "y":78},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdbc62f6347d45e195b990c993dcc4c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":937,
                  "y":78},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"1b3580cc3eea4ed2accdf5c9855f0041",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":943,
              "y":78},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e646b21b19244c1693d26eb31fd63061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":943,
                  "y":78},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"37ab60369280401087279061031f03f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":950,
              "y":78},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26dedfbc40fd402cb6e6cf5f993a86c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":950,
                  "y":78},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"9ecace31687e4dacb0cca514f1acf21b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":973,
              "y":64},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b23928b572e432db700f25252753f36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":973,
                  "y":64},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u27.png"}},
{
          "id":"d67b4467ef7d4e9a8e524796c20f1b4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":975,
              "y":67},
            "size":{
              "width":19,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"556c2ad9653c4cd5a79a950e783e6715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":975,
                  "y":67},
                "size":{
                  "width":19,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u58.png"}},
{
          "id":"3f3ea2b6961b46c3bce01c2ff102c62d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":975,
              "y":73},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75512458c33943e390d7293eb1e7e97c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":975,
                  "y":73},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u60.png"}},
{
          "id":"4b9ea3bca2534459a255f6a420bf16de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":975,
              "y":78},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b790ebaa030b4923bf0c72ab107c6d3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":975,
                  "y":78},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u60.png"}},
{
          "id":"13337489b9d34e9598e73b338a96ba4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":783,
              "y":60},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c45c827dc3c74e12bca0fe9c87ff1e59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":783,
                  "y":60},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a40089e6130c473fbcd18f9fc2b630f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":218},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a9521f4a22d4c7992cc8f0fa57c4252",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":218},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc1d9db6c22a4a7798b3028622a80698",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":236},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1efdac2f5c54a9088d0845c1651f247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":236},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c375b2e5750542f0958cc50a7a6344bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":336},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09950c8e3ccf4770a78424edd59004b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":336},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e6e5ea64e154bf284799536931aec58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":354},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61773b5635284b34a75dd5f2586bc958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":354},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad917c7c1db248a1bc66deafc0495262",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":139},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d6e606737734dc5a08157808e4e5261",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":139},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4681eeaa2a044b40bc5510ae4cbd4f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":255},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bab0d54fd09a47c2b51a075e9611530e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":255},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e7546b298ae4108b93ab909328f5fb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":370},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39a7af50f4f04faa8804a3274cb087c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":370},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"118d3035b5234f399b3bff694d3580a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":336},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3319ca4d66f4c20af6b2ced4975d2df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":336},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"b5d7d6305a7d4f56b5286f65caf8d1a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":218},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d00d9acaf37461e8084678bd44f8738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":218},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"65c33b8facd44de2b2c5b3cc542aa913",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":102},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6472f6066ca427f9ef51b96cb8689db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":446,
                  "y":102},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"9633f882164a4f4a98201227a7bd7118",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":200,
              "height":383},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f65ce2b82a04a26bb9216f7b049f3e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":200,
                  "height":383},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u120.png"}},
{
          "id":"0816c4375d3d4457a238b2a2afc0941a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1094,
              "y":50},
            "size":{
              "width":10,
              "height":383},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/employee_dashboard/u122_line.png"}},
{
          "id":"afe19f8fa14643ebbdf403f187a956b2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":644,
              "y":50},
            "size":{
              "width":10,
              "height":383},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/employee_dashboard/u122_line.png"}},
{
          "id":"cea6d9a2e05440fb84d4409c68eae786",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":102},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f969a49456d34e65ac9e870feee00b67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":835,
              "y":117},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2fe4714b4a8428b87fd2359a8786a2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":835,
                  "y":117},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c0915761d45479e98026da2e482690f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":906,
              "y":120},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"437532d43b324399879eb8b974d74db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":906,
                  "y":120},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"4ddcf60a6b3a4a0c84b22b769234153d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"63e1251d8da54dcdb33dd6d4def04832",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c3d56b8804094e519836cba4ec98aa37"}]}},
  "masters":{
    "643f38a9e3bf4284950d1c1c8c2e016e":{
      "packageId":"643f38a9e3bf4284950d1c1c8c2e016e",
      "type":"Axure:Master",
      "name":"Project pattern",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1eb774dd84b74f679e1c1bd422be5508",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":226,
                "height":66}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d32dc69dba6444a0a9f03b52371ab6e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":226,
                    "height":66}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u1.png"}},
{
            "id":"e3153abc043e4f838744bce786afd3b6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":5,
                "y":6},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2bda756d87a14d1ea5c2da050e9c4b14",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":5,
                    "y":6},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u3.png"}},
{
            "id":"b375c3123ad64d959cb0ff599c8834ff",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":226,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"11bf32fcaa884eebb40a9d33f7b528d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":226,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u5.png"}},
{
            "id":"d899b250a27f4396b89669821051e0c0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":162,
                "y":71},
              "size":{
                "width":52,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ba56414f5f3b4d4ea4f5934815b8a07e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":162,
                    "y":71},
                  "size":{
                    "width":52,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Project (employee view) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"project__employee_view_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/employee_dashboard/u7.png"}}]}},
    "6a4d007a25584617bcd0a52a01713c4b":{
      "packageId":"6a4d007a25584617bcd0a52a01713c4b",
      "type":"Axure:Master",
      "name":"Employee pattern",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ea707c57163c4eb3bbe0a0eae94e2f9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":226,
                "height":66}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"db5cb9a4a293404890a80441016cfee6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":226,
                    "height":66}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u1.png",
              "normal~":"images/employee_dashboard/u1.png",
              "normal~":"images/employee_dashboard/u1.png"}},
{
            "id":"49d5ecd6f645413dbb73b3cbe20bd0b8",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":5,
                "y":6},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bf9063c40e48449a8539cf43248c30f8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":5,
                    "y":6},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u3.png",
              "normal~":"images/employee_dashboard/u3.png",
              "normal~":"images/employee_dashboard/u3.png"}},
{
            "id":"31fdf76ac5724b97856046fb2ee26990",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":226,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59bdac84887746fd9b4718cce6c9033a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":226,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u5.png",
              "normal~":"images/employee_dashboard/u5.png",
              "normal~":"images/employee_dashboard/u5.png"}},
{
            "id":"0afa7d21d0f140d0aa90d7bf51afefb4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":162,
                "y":71},
              "size":{
                "width":52,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c114114f712f46eba4108ce5c8609025",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":162,
                    "y":71},
                  "size":{
                    "width":52,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Employee (employee view) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"employee__employee_view_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/employee_dashboard/u7.png",
              "normal~":"images/employee_dashboard/u7.png",
              "normal~":"images/employee_dashboard/u7.png"}}]}},
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u130.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u132.png"}}]}},
    "c3d56b8804094e519836cba4ec98aa37":{
      "packageId":"c3d56b8804094e519836cba4ec98aa37",
      "type":"Axure:Master",
      "name":"Employee menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c53b0307d0da4147910ccf3ed931a762",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Employee dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"employee_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"8f5f1397212f454fab65667c4379d05a",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Employee profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"employee_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "e9fac6ca660c49ee81e90cd01031aff1":{
      "scriptId":"u0",
      "1eb774dd84b74f679e1c1bd422be5508":{
        "scriptId":"u1"},
      "d32dc69dba6444a0a9f03b52371ab6e1":{
        "scriptId":"u2"},
      "e3153abc043e4f838744bce786afd3b6":{
        "scriptId":"u3"},
      "2bda756d87a14d1ea5c2da050e9c4b14":{
        "scriptId":"u4"},
      "b375c3123ad64d959cb0ff599c8834ff":{
        "scriptId":"u5"},
      "11bf32fcaa884eebb40a9d33f7b528d4":{
        "scriptId":"u6"},
      "d899b250a27f4396b89669821051e0c0":{
        "scriptId":"u7"},
      "ba56414f5f3b4d4ea4f5934815b8a07e":{
        "scriptId":"u8"}},
    "3432a52f6e864bfdaec6544355732606":{
      "scriptId":"u9",
      "ea707c57163c4eb3bbe0a0eae94e2f9d":{
        "scriptId":"u10"},
      "db5cb9a4a293404890a80441016cfee6":{
        "scriptId":"u11"},
      "49d5ecd6f645413dbb73b3cbe20bd0b8":{
        "scriptId":"u12"},
      "bf9063c40e48449a8539cf43248c30f8":{
        "scriptId":"u13"},
      "31fdf76ac5724b97856046fb2ee26990":{
        "scriptId":"u14"},
      "59bdac84887746fd9b4718cce6c9033a":{
        "scriptId":"u15"},
      "0afa7d21d0f140d0aa90d7bf51afefb4":{
        "scriptId":"u16"},
      "c114114f712f46eba4108ce5c8609025":{
        "scriptId":"u17"}},
    "dc25ed2e0d2040f394152d5b99d53b41":{
      "scriptId":"u18",
      "ea707c57163c4eb3bbe0a0eae94e2f9d":{
        "scriptId":"u19"},
      "db5cb9a4a293404890a80441016cfee6":{
        "scriptId":"u20"},
      "49d5ecd6f645413dbb73b3cbe20bd0b8":{
        "scriptId":"u21"},
      "bf9063c40e48449a8539cf43248c30f8":{
        "scriptId":"u22"},
      "31fdf76ac5724b97856046fb2ee26990":{
        "scriptId":"u23"},
      "59bdac84887746fd9b4718cce6c9033a":{
        "scriptId":"u24"},
      "0afa7d21d0f140d0aa90d7bf51afefb4":{
        "scriptId":"u25"},
      "c114114f712f46eba4108ce5c8609025":{
        "scriptId":"u26"}},
    "f5811b1d9a6c44879f877a1fa830c6e2":{
      "scriptId":"u27"},
    "5c2ea37a2a8c4e1cb2e59097976a29aa":{
      "scriptId":"u28"},
    "6f26d5107ba04f80b126f9422eb557aa":{
      "scriptId":"u29"},
    "4a9200af324d4bec9e6dfec4c6ef6979":{
      "scriptId":"u30"},
    "3d67a0932fb140d1bb4c2373e27e32a9":{
      "scriptId":"u31",
      "ea707c57163c4eb3bbe0a0eae94e2f9d":{
        "scriptId":"u32"},
      "db5cb9a4a293404890a80441016cfee6":{
        "scriptId":"u33"},
      "49d5ecd6f645413dbb73b3cbe20bd0b8":{
        "scriptId":"u34"},
      "bf9063c40e48449a8539cf43248c30f8":{
        "scriptId":"u35"},
      "31fdf76ac5724b97856046fb2ee26990":{
        "scriptId":"u36"},
      "59bdac84887746fd9b4718cce6c9033a":{
        "scriptId":"u37"},
      "0afa7d21d0f140d0aa90d7bf51afefb4":{
        "scriptId":"u38"},
      "c114114f712f46eba4108ce5c8609025":{
        "scriptId":"u39"}},
    "3092662f439642b8b63e413aaccafb84":{
      "scriptId":"u40"},
    "df89ef7904b84b488ef1ccaf65b0bcd2":{
      "scriptId":"u41"},
    "447741136e2e4b1180d79f8ac10d7ab6":{
      "scriptId":"u42"},
    "e0e743ebcff048b6bff1287cdfcbbf99":{
      "scriptId":"u43"},
    "8c2fc04af4804e86a299262be80abe8a":{
      "scriptId":"u44"},
    "5519db8e426e475d8454e1fe3f244e1b":{
      "scriptId":"u45"},
    "2e8f8c34a05e4eaeb2c5bb9f27e73c2b":{
      "scriptId":"u46"},
    "140f29f694574f689b43686e1601b6f7":{
      "scriptId":"u47"},
    "6e8fca4624524cd39d51ad4622afcd70":{
      "scriptId":"u48"},
    "8621480ae46a47d68c6d211a3455b74c":{
      "scriptId":"u49"},
    "91bcab52159c4d53a2e065b7848933b8":{
      "scriptId":"u50"},
    "bcbb205555174e1ea7072d41a20731a2":{
      "scriptId":"u51"},
    "5bf2831a0bde4db2824e15d68bee9700":{
      "scriptId":"u52"},
    "982343d3d58a45d48e67a50d864e0384":{
      "scriptId":"u53"},
    "70445390bff744138de7ed93847a2fc0":{
      "scriptId":"u54"},
    "25bc81a3bad04f1f9b08c31b3b37e6fe":{
      "scriptId":"u55"},
    "fa093eee26964c9bb3e20ea1ba178aa7":{
      "scriptId":"u56"},
    "73aa351b81e941d2baf77acbe2aa86b4":{
      "scriptId":"u57"},
    "d31b438aa706476491d9979eb2d47a22":{
      "scriptId":"u58"},
    "8f20b1265267432d8faafe14f5a76e19":{
      "scriptId":"u59"},
    "2af21bc5cc5e480abf30f90d82f6a11b":{
      "scriptId":"u60"},
    "8285d957ff8c449b9eef23aa4359a157":{
      "scriptId":"u61"},
    "62ba98d3faf2443e92493396fdaefeca":{
      "scriptId":"u62"},
    "ae349578d98a4c92b8918baf43ec27be":{
      "scriptId":"u63"},
    "357bf8f95edd46ddbb0290eb68aa322e":{
      "scriptId":"u64"},
    "3560c573f8194c029d7a9f49ee71ed92":{
      "scriptId":"u65"},
    "56eca7f2e41844e8979961b0b622c148":{
      "scriptId":"u66"},
    "c27c7426e96c4f9c9eccf9b206fcce12":{
      "scriptId":"u67"},
    "ad102312a55244528a8c35070c586145":{
      "scriptId":"u68"},
    "6ff574e960cb48d2b5bcd7f1897efe2a":{
      "scriptId":"u69"},
    "bb7cbf94480e4758b10b21e67c4ad4e6":{
      "scriptId":"u70"},
    "a302bf4ca2714d9ab9e327761743a85c":{
      "scriptId":"u71"},
    "b4ed0b08920447a189691dd48f0841b6":{
      "scriptId":"u72"},
    "d29a3b87bada48678596a1833cc04e34":{
      "scriptId":"u73"},
    "9cf4addb9ccc4d48a8a17c97e2f7637a":{
      "scriptId":"u74"},
    "c669333d457c438b8be9cc40443414c3":{
      "scriptId":"u75"},
    "c1b766e0f16541a2b8521ea6f5f34ff9":{
      "scriptId":"u76"},
    "f553d5c3a2244d42826d3472e633f453":{
      "scriptId":"u77"},
    "62db7370aeba41ecb67a795c65c2f9c1":{
      "scriptId":"u78"},
    "6568e04cb0dd40048559670d36060990":{
      "scriptId":"u79"},
    "05ab40e20d9a4074b51d8999341ac27d":{
      "scriptId":"u80"},
    "6721914615ee4bc68107926282abfe6d":{
      "scriptId":"u81"},
    "d2c9f0cc37de4ce6b73fb73f8864bdb6":{
      "scriptId":"u82"},
    "ff8167eab1604c98a84db1f61a68cf5d":{
      "scriptId":"u83"},
    "52c51f7d0f2946b09a182344133480cd":{
      "scriptId":"u84"},
    "bdbc62f6347d45e195b990c993dcc4c4":{
      "scriptId":"u85"},
    "1b3580cc3eea4ed2accdf5c9855f0041":{
      "scriptId":"u86"},
    "e646b21b19244c1693d26eb31fd63061":{
      "scriptId":"u87"},
    "37ab60369280401087279061031f03f5":{
      "scriptId":"u88"},
    "26dedfbc40fd402cb6e6cf5f993a86c1":{
      "scriptId":"u89"},
    "9ecace31687e4dacb0cca514f1acf21b":{
      "scriptId":"u90"},
    "9b23928b572e432db700f25252753f36":{
      "scriptId":"u91"},
    "d67b4467ef7d4e9a8e524796c20f1b4f":{
      "scriptId":"u92"},
    "556c2ad9653c4cd5a79a950e783e6715":{
      "scriptId":"u93"},
    "3f3ea2b6961b46c3bce01c2ff102c62d":{
      "scriptId":"u94"},
    "75512458c33943e390d7293eb1e7e97c":{
      "scriptId":"u95"},
    "4b9ea3bca2534459a255f6a420bf16de":{
      "scriptId":"u96"},
    "b790ebaa030b4923bf0c72ab107c6d3f":{
      "scriptId":"u97"},
    "13337489b9d34e9598e73b338a96ba4c":{
      "scriptId":"u98"},
    "c45c827dc3c74e12bca0fe9c87ff1e59":{
      "scriptId":"u99"},
    "a40089e6130c473fbcd18f9fc2b630f0":{
      "scriptId":"u100"},
    "5a9521f4a22d4c7992cc8f0fa57c4252":{
      "scriptId":"u101"},
    "fc1d9db6c22a4a7798b3028622a80698":{
      "scriptId":"u102"},
    "d1efdac2f5c54a9088d0845c1651f247":{
      "scriptId":"u103"},
    "c375b2e5750542f0958cc50a7a6344bd":{
      "scriptId":"u104"},
    "09950c8e3ccf4770a78424edd59004b3":{
      "scriptId":"u105"},
    "8e6e5ea64e154bf284799536931aec58":{
      "scriptId":"u106"},
    "61773b5635284b34a75dd5f2586bc958":{
      "scriptId":"u107"},
    "ad917c7c1db248a1bc66deafc0495262":{
      "scriptId":"u108"},
    "0d6e606737734dc5a08157808e4e5261":{
      "scriptId":"u109"},
    "4681eeaa2a044b40bc5510ae4cbd4f07":{
      "scriptId":"u110"},
    "bab0d54fd09a47c2b51a075e9611530e":{
      "scriptId":"u111"},
    "9e7546b298ae4108b93ab909328f5fb4":{
      "scriptId":"u112"},
    "39a7af50f4f04faa8804a3274cb087c5":{
      "scriptId":"u113"},
    "118d3035b5234f399b3bff694d3580a1":{
      "scriptId":"u114"},
    "d3319ca4d66f4c20af6b2ced4975d2df":{
      "scriptId":"u115"},
    "b5d7d6305a7d4f56b5286f65caf8d1a9":{
      "scriptId":"u116"},
    "2d00d9acaf37461e8084678bd44f8738":{
      "scriptId":"u117"},
    "65c33b8facd44de2b2c5b3cc542aa913":{
      "scriptId":"u118"},
    "d6472f6066ca427f9ef51b96cb8689db":{
      "scriptId":"u119"},
    "9633f882164a4f4a98201227a7bd7118":{
      "scriptId":"u120"},
    "3f65ce2b82a04a26bb9216f7b049f3e8":{
      "scriptId":"u121"},
    "0816c4375d3d4457a238b2a2afc0941a":{
      "scriptId":"u122"},
    "afe19f8fa14643ebbdf403f187a956b2":{
      "scriptId":"u123"},
    "cea6d9a2e05440fb84d4409c68eae786":{
      "scriptId":"u124"},
    "f969a49456d34e65ac9e870feee00b67":{
      "scriptId":"u125"},
    "b2fe4714b4a8428b87fd2359a8786a2c":{
      "scriptId":"u126"},
    "2c0915761d45479e98026da2e482690f":{
      "scriptId":"u127"},
    "437532d43b324399879eb8b974d74db5":{
      "scriptId":"u128"},
    "4ddcf60a6b3a4a0c84b22b769234153d":{
      "scriptId":"u129",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u130"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u131"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u132"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u133"}},
    "63e1251d8da54dcdb33dd6d4def04832":{
      "scriptId":"u134",
      "c53b0307d0da4147910ccf3ed931a762":{
        "scriptId":"u135"},
      "8f5f1397212f454fab65667c4379d05a":{
        "scriptId":"u136"}}}});