$axure.loadCurrentPage({
  "url":"project__client_view_.html",
  "generationDate":new Date(1439394926423.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fe044d3b3b3845b7a1ee1f36ea747c78",
    "type":"Axure:Page",
    "name":"Project (client view)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7ee9948a8d42484c9757162bd263503f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1100,
              "height":900},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73c8380ebf8a4dce992bac5239872f3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1100,
                  "height":900},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/project__employee_view_/u8.png"}},
{
          "id":"0cf60d557b4a4f47af4d2778b97bf617",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":70},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d30e95c2b2a4aa1a6f814908bfccce1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":70},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u10.png"}},
{
          "id":"a37ad5a4bc684be78899a0c93e7b93df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":70},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23bbeb66a73f4151bdf05c00a00fe6d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":70},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54bc58c7d12740b0aaaa8d798047c1c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":138},
            "size":{
              "width":201,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1ba6301a5874d7f9ac0f0b059147ad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":138},
                "size":{
                  "width":201,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec2a061c6f6f4dbf948e053bdc2d444c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":169},
            "size":{
              "width":460,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea58c72ef58f4b32bb31c4a7035ef2b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":169},
                "size":{
                  "width":460,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7afb8e911704b6c93d938c8444f5891",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":104},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91b4c2109a8e4b2db766c18a5a38dd3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":104},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfaabcac6593475ebfc49791a9b99c25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":78},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65824e19163b4f36a8bede3ca41a2cab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":78},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"5841f7faeeaa46fb9bdc33f333f996df",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"f588d9aea09843d19828bd1a2907947f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7960479542a744d09a89949d89357fee"}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u130.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u132.png"}}]}},
    "7960479542a744d09a89949d89357fee":{
      "packageId":"7960479542a744d09a89949d89357fee",
      "type":"Axure:Master",
      "name":"Client menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c1c2bf7a73b142e98889e67c858f6199",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Client dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"client_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"532b2c922e8e4042a2f400488f29927e",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Client profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"client_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "7ee9948a8d42484c9757162bd263503f":{
      "scriptId":"u0"},
    "73c8380ebf8a4dce992bac5239872f3e":{
      "scriptId":"u1"},
    "0cf60d557b4a4f47af4d2778b97bf617":{
      "scriptId":"u2"},
    "2d30e95c2b2a4aa1a6f814908bfccce1":{
      "scriptId":"u3"},
    "a37ad5a4bc684be78899a0c93e7b93df":{
      "scriptId":"u4"},
    "23bbeb66a73f4151bdf05c00a00fe6d0":{
      "scriptId":"u5"},
    "54bc58c7d12740b0aaaa8d798047c1c4":{
      "scriptId":"u6"},
    "f1ba6301a5874d7f9ac0f0b059147ad6":{
      "scriptId":"u7"},
    "ec2a061c6f6f4dbf948e053bdc2d444c":{
      "scriptId":"u8"},
    "ea58c72ef58f4b32bb31c4a7035ef2b3":{
      "scriptId":"u9"},
    "a7afb8e911704b6c93d938c8444f5891":{
      "scriptId":"u10"},
    "91b4c2109a8e4b2db766c18a5a38dd3a":{
      "scriptId":"u11"},
    "bfaabcac6593475ebfc49791a9b99c25":{
      "scriptId":"u12"},
    "65824e19163b4f36a8bede3ca41a2cab":{
      "scriptId":"u13"},
    "5841f7faeeaa46fb9bdc33f333f996df":{
      "scriptId":"u14",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u15"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u16"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u17"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u18"}},
    "f588d9aea09843d19828bd1a2907947f":{
      "scriptId":"u19",
      "c1c2bf7a73b142e98889e67c858f6199":{
        "scriptId":"u20"},
      "532b2c922e8e4042a2f400488f29927e":{
        "scriptId":"u21"}}}});