$axure.loadCurrentPage({
  "url":"employee.html",
  "generationDate":new Date(1438957015226.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"79f6bb27891d4f2a92bdddf7844b71f4",
    "type":"Axure:Page",
    "name":"Employee",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d77d0eb6a2664b7da001fb08844c48aa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"9a2bea0dab994e1f8250cbd7c5447bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":51,
              "y":0},
            "size":{
              "width":749,
              "height":840},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"502f7fc92f6b4ff09dbb8d6b224233c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":51,
                  "y":0},
                "size":{
                  "width":749,
                  "height":840},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee/u5.png"}},
{
          "id":"3fda5641049149ad9e8be6131de04527",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":20},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f1c05f46a049eaaa4438024c821c47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":20},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee/u7.png"}},
{
          "id":"4df6d4fe36b84e86b059c10140edd02a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":20},
            "size":{
              "width":93,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eff3890ce3547728d948c9f568d0bf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":20},
                "size":{
                  "width":93,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64c16beb113f4925a63a561138a0ab1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":52},
            "size":{
              "width":152,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757738fa9c494705990fd403fe326c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":52},
                "size":{
                  "width":152,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4e8681f8d6649a1a8cfce0e4a821a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":153},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f35f0c41fc7b49f2a56c0b17c39841ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":153},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86767845b4be45a5b1a2a555d1922eb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":123},
            "size":{
              "width":98,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a467bc4e99d341339ae8a5884c88763a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":123},
                "size":{
                  "width":98,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b076e9015db43e8b3d96e42712e055c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":181},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3017bcb36fda4e889b0c87ff45e443c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":181},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65438c9efb324f3bb35cc627de573378",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":394},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"924a39aeeedf4690adba0a4693e09747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":394},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05a72f39c2b1454db95dfe57b4d711dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":428},
            "size":{
              "width":570,
              "height":186}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b932f9064a0b48109611264706e1252d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":428},
                "size":{
                  "width":570,
                  "height":186}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee/u21.png"}},
{
          "id":"ab4d2c8a39e7410f84587ea13f67bc83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "underline":true,
            "location":{
              "x":225,
              "y":435},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96aa8969ed8e42debe7f6a0c23e2df47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "underline":true,
                "location":{
                  "x":225,
                  "y":435},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6cd1eabe00f48048efffd0b5e0b21f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":225,
              "y":466},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff68bb203a544aaaf27468edbfe2fff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":225,
                  "y":466},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40e38f55a9a74fc08e89e5ab8ac75ad3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":225,
              "y":496},
            "size":{
              "width":295,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db53bf8311ce443ab9dcc6de2b8e4102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":225,
                  "y":496},
                "size":{
                  "width":295,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d35e62d526934477a0fb0ccefa369b02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":225,
              "y":529},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb6e15a656134eb985a67a22f85f0b50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":225,
                  "y":529},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6ce4ca88bd14748a747da43e4588680",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":624},
            "size":{
              "width":570,
              "height":186}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f159abdc1e045b0a8610eb22f1bc308",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":624},
                "size":{
                  "width":570,
                  "height":186}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee/u21.png"}},
{
          "id":"7fcdcfe24e054f7f93802350d67b2905",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "underline":true,
            "location":{
              "x":225,
              "y":631},
            "size":{
              "width":103,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d7b75beccda4b299cd6890a2722cb1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "underline":true,
                "location":{
                  "x":225,
                  "y":631},
                "size":{
                  "width":103,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bdec699876d4a0ab148c2c6dd8be7b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":225,
              "y":662},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d9e06172891429d81621e75cd4e47de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":225,
                  "y":662},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25502a6291ad4508932ca9f762f07407",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":225,
              "y":692},
            "size":{
              "width":295,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a4d73563fd42508b24a72e5a8d5f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":225,
                  "y":692},
                "size":{
                  "width":295,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91d8ca9ee6d849a093b5eb46c70a5ecf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":225,
              "y":725},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd861d3ddc5a4ddd8b0255159f81750b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":225,
                  "y":725},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98a29d206a8747498479c890b14f4ea6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":378,
              "y":52},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5f843105a3d474d92638b38c79e1b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":378,
                  "y":52},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcc0688166584a4282119b12ffcf3bfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":80},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf8dba71cfb047e3b59fce8b3f3f0a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":80},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"896ee3ac2b4347b19dc1653c8bcc2250",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":320,
              "y":80},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"156b7c73b84d4becac3035c19ef8d88b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":320,
                  "y":80},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c8869c4935a4746af450e849d3dbb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":262},
            "size":{
              "width":108,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82e7182187784e989ed23981ad00a608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":262},
                "size":{
                  "width":108,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3106e2096c634a0daa622b974a261d95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":292},
            "size":{
              "width":333,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"328dc12e2ed140a3b11342f098e046be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":292},
                "size":{
                  "width":333,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cdd18092dbd41fabe3be04a463d2267",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":317},
            "size":{
              "width":333,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f63d3507ee24b2593dae19fb20483f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":317},
                "size":{
                  "width":333,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb1baf51244542a28d5938deece8824b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":343},
            "size":{
              "width":333,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad2ab919117d46e3a9738b74a7fc64ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":343},
                "size":{
                  "width":333,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9da8e6598207469e92b722d6c131c65d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":210,
              "y":207},
            "size":{
              "width":128,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc7f05f311fd45389dfa5c65d863ac0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":210,
                  "y":207},
                "size":{
                  "width":128,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25ecf11dc7f845bab427ef13e5f0ef05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":70,
              "y":140},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b30d05c1961d4d03845abbdb81df6aeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":70,
                  "y":140},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":51,
                "height":900},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":51,
                    "height":900},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}}]}}},
  "objectPaths":{
    "d77d0eb6a2664b7da001fb08844c48aa":{
      "scriptId":"u0",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u1"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u2"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u3"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u4"}},
    "9a2bea0dab994e1f8250cbd7c5447bc1":{
      "scriptId":"u5"},
    "502f7fc92f6b4ff09dbb8d6b224233c4":{
      "scriptId":"u6"},
    "3fda5641049149ad9e8be6131de04527":{
      "scriptId":"u7"},
    "57f1c05f46a049eaaa4438024c821c47":{
      "scriptId":"u8"},
    "4df6d4fe36b84e86b059c10140edd02a":{
      "scriptId":"u9"},
    "2eff3890ce3547728d948c9f568d0bf3":{
      "scriptId":"u10"},
    "64c16beb113f4925a63a561138a0ab1f":{
      "scriptId":"u11"},
    "757738fa9c494705990fd403fe326c9b":{
      "scriptId":"u12"},
    "e4e8681f8d6649a1a8cfce0e4a821a29":{
      "scriptId":"u13"},
    "f35f0c41fc7b49f2a56c0b17c39841ae":{
      "scriptId":"u14"},
    "86767845b4be45a5b1a2a555d1922eb4":{
      "scriptId":"u15"},
    "a467bc4e99d341339ae8a5884c88763a":{
      "scriptId":"u16"},
    "3b076e9015db43e8b3d96e42712e055c":{
      "scriptId":"u17"},
    "3017bcb36fda4e889b0c87ff45e443c4":{
      "scriptId":"u18"},
    "65438c9efb324f3bb35cc627de573378":{
      "scriptId":"u19"},
    "924a39aeeedf4690adba0a4693e09747":{
      "scriptId":"u20"},
    "05a72f39c2b1454db95dfe57b4d711dd":{
      "scriptId":"u21"},
    "b932f9064a0b48109611264706e1252d":{
      "scriptId":"u22"},
    "ab4d2c8a39e7410f84587ea13f67bc83":{
      "scriptId":"u23"},
    "96aa8969ed8e42debe7f6a0c23e2df47":{
      "scriptId":"u24"},
    "d6cd1eabe00f48048efffd0b5e0b21f1":{
      "scriptId":"u25"},
    "7ff68bb203a544aaaf27468edbfe2fff":{
      "scriptId":"u26"},
    "40e38f55a9a74fc08e89e5ab8ac75ad3":{
      "scriptId":"u27"},
    "db53bf8311ce443ab9dcc6de2b8e4102":{
      "scriptId":"u28"},
    "d35e62d526934477a0fb0ccefa369b02":{
      "scriptId":"u29"},
    "fb6e15a656134eb985a67a22f85f0b50":{
      "scriptId":"u30"},
    "f6ce4ca88bd14748a747da43e4588680":{
      "scriptId":"u31"},
    "0f159abdc1e045b0a8610eb22f1bc308":{
      "scriptId":"u32"},
    "7fcdcfe24e054f7f93802350d67b2905":{
      "scriptId":"u33"},
    "8d7b75beccda4b299cd6890a2722cb1c":{
      "scriptId":"u34"},
    "2bdec699876d4a0ab148c2c6dd8be7b5":{
      "scriptId":"u35"},
    "0d9e06172891429d81621e75cd4e47de":{
      "scriptId":"u36"},
    "25502a6291ad4508932ca9f762f07407":{
      "scriptId":"u37"},
    "84a4d73563fd42508b24a72e5a8d5f02":{
      "scriptId":"u38"},
    "91d8ca9ee6d849a093b5eb46c70a5ecf":{
      "scriptId":"u39"},
    "fd861d3ddc5a4ddd8b0255159f81750b":{
      "scriptId":"u40"},
    "98a29d206a8747498479c890b14f4ea6":{
      "scriptId":"u41"},
    "e5f843105a3d474d92638b38c79e1b27":{
      "scriptId":"u42"},
    "fcc0688166584a4282119b12ffcf3bfd":{
      "scriptId":"u43"},
    "cf8dba71cfb047e3b59fce8b3f3f0a9f":{
      "scriptId":"u44"},
    "896ee3ac2b4347b19dc1653c8bcc2250":{
      "scriptId":"u45"},
    "156b7c73b84d4becac3035c19ef8d88b":{
      "scriptId":"u46"},
    "5c8869c4935a4746af450e849d3dbb8d":{
      "scriptId":"u47"},
    "82e7182187784e989ed23981ad00a608":{
      "scriptId":"u48"},
    "3106e2096c634a0daa622b974a261d95":{
      "scriptId":"u49"},
    "328dc12e2ed140a3b11342f098e046be":{
      "scriptId":"u50"},
    "4cdd18092dbd41fabe3be04a463d2267":{
      "scriptId":"u51"},
    "2f63d3507ee24b2593dae19fb20483f0":{
      "scriptId":"u52"},
    "cb1baf51244542a28d5938deece8824b":{
      "scriptId":"u53"},
    "ad2ab919117d46e3a9738b74a7fc64ab":{
      "scriptId":"u54"},
    "9da8e6598207469e92b722d6c131c65d":{
      "scriptId":"u55"},
    "fc7f05f311fd45389dfa5c65d863ac0e":{
      "scriptId":"u56"},
    "25ecf11dc7f845bab427ef13e5f0ef05":{
      "scriptId":"u57"},
    "b30d05c1961d4d03845abbdb81df6aeb":{
      "scriptId":"u58"}}});