$axure.loadCurrentPage({
  "url":"client_dashboard.html",
  "generationDate":new Date(1439394926213.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9148de1c2e7c475b89494f683e5255ca",
    "type":"Axure:Page",
    "name":"Client dashboard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e2e8779d8feb49cba67aabe2d1aca2f9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":330}},
          "adaptiveStyles":{
},
          "masterId":"cb2317a61a23419e8f00adf3082fa67c"},
{
          "id":"f641ef2cb7e94f89b864a653cad8a0b4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":213}},
          "adaptiveStyles":{
},
          "masterId":"cb2317a61a23419e8f00adf3082fa67c"},
{
          "id":"a89e78b631d04e30aa0db60dc5f04220",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":477,
              "y":62},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cab9bee4c099415b9a7f2254a84126f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":477,
                  "y":62},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u27.png"}},
{
          "id":"56e757cde87246d5b5d3d1f3661fe1c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":480,
              "y":64},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eab7f09c1b7423b95fe01cb95023d59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":480,
                  "y":64},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"98b3688aaa5749beb9721137bce71b78",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":304.5,
              "y":97}},
          "adaptiveStyles":{
},
          "masterId":"cb2317a61a23419e8f00adf3082fa67c"},
{
          "id":"dfe4f464664a4d3aa19a3ee567153498",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":486,
              "y":64},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2612b685b42462aba51c43461405856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":486,
                  "y":64},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"fe71bf3dd1a3478aae12c8438cc5243b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":493,
              "y":64},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95da6d7631b41158c69f1624e945d2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":493,
                  "y":64},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"b61c3d5879f04d658e69916859e1fcab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":480,
              "y":70},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f535a9c4aa4f1b8232e265a4c8276b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":480,
                  "y":70},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"deeb8b1a79454a2788684c6711b2dd0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":486,
              "y":70},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04a3267c1fbe4bea93d6340c20b7824b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":486,
                  "y":70},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"1ca7d487cd284aa3bf57e3c534e454a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":493,
              "y":70},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb6d1059115845e488f7722f729ee239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":493,
                  "y":70},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"39ed9c37236b45b5b93e0e7f295c84f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":480,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60e81b4ea8784e009e10831e6ca5a247",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":480,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"bbb422fcb63a4649b6905f8cc962dd3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":486,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f394823a325b4ebdaf76ec5d287b3774",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":486,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"8c8c9c1be70f409dbfe55be5d87c31ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":493,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a651bb02d5a48dc8e392951e7338052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":493,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"c71c3b4bfe134fdfa21d29412e820266",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":516,
              "y":62},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af73a8f7508c4d6a8b2ddd9b0429985c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":516,
                  "y":62},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u27.png"}},
{
          "id":"ce04d4203a224a0092ed5044b9269015",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":518,
              "y":65},
            "size":{
              "width":19,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f06786e5a60340de90d641ca5628864f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":518,
                  "y":65},
                "size":{
                  "width":19,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u58.png"}},
{
          "id":"383f6a7174d54014bd32047db89a48ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":518,
              "y":71},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1fbdab57f6a4c0989cbe17209e95f6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":518,
                  "y":71},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u60.png"}},
{
          "id":"1e76c5bf78804b818123061f15ced10f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":518,
              "y":76},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a073b8d269f048798c2caac11e1409fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":518,
                  "y":76},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u60.png"}},
{
          "id":"671ea9f5bb97473cbb66b9d2bcd81c3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":102},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ac4f5025552452fa791d5fc385d2347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":102},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b603e1c0e5c04344912e83e834a0fb9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":120},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56ba62a3543443499dd1f82b800cdbab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":120},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a9d25d921ce414187086ee455044875",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":322,
              "y":60},
            "size":{
              "width":104,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4387bc4caf04dc5b88856f691595072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":322,
                  "y":60},
                "size":{
                  "width":104,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41aebad040454a29b99c709f85c043bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":934,
              "y":64},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c51c4d2ea1d940919081d34debc91fd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":934,
                  "y":64},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u27.png"}},
{
          "id":"2e102b37d61c4ef693ebf2ec6b05e564",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":937,
              "y":66},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7278df09c8d4829a3dc3dea52a21544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":937,
                  "y":66},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"c118b87609b44a08acf2f43c21fe259a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":943,
              "y":66},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6b4bd2a8cc749c58588b066833a29f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":943,
                  "y":66},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"1dddfd69d0d64735be80b1157b4fee6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":950,
              "y":66},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d420c54f0e843059f474ddbd93e0469",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":950,
                  "y":66},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"1a31f59e09484de88e9b8434dcb9e875",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":937,
              "y":72},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4868105572bd483e9c3d62f4bb8b35d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":937,
                  "y":72},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"a5072597d27f458c8b81a55310825271",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":943,
              "y":72},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"977c7db61e614f77a274d396e57a83b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":943,
                  "y":72},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"9aaa058d023d45bf93b714f3ae99d28e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":950,
              "y":72},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1716bea8727845cb958b1c0aa6df8d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":950,
                  "y":72},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"fa2de2bff6a84e53a6fae9d25d7287d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":937,
              "y":78},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec0e9f97ba04d7e93d1358635d93c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":937,
                  "y":78},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"bb73ffa65e7044549f3ce32627d3b07c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":943,
              "y":78},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04b334e0d0684a2f8898bedfe4d7fb5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":943,
                  "y":78},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"33c45907761e4958a8034be915f4e25c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":950,
              "y":78},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87a923daadad418bb6b9de6b0f10760e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":950,
                  "y":78},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u29.png"}},
{
          "id":"5ec6ba8e689e401a80b19c78d8075c0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":973,
              "y":64},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64a9ec669eee474e941bef2dc2b637fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":973,
                  "y":64},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u27.png"}},
{
          "id":"dffbe8e3fb184974b982a55252e5f770",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":975,
              "y":67},
            "size":{
              "width":19,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b7923a6c8a44148a0aa0806a2d3be8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":975,
                  "y":67},
                "size":{
                  "width":19,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u58.png"}},
{
          "id":"ce96c65b85404492b12348393cafce37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":975,
              "y":73},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3b073ee6fec422189c14b087cb8ee10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":975,
                  "y":73},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u60.png"}},
{
          "id":"233b5f5861b340aca611a33235bb71f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":975,
              "y":78},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f807e224a8194c48bfcdca2fb923b2a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":975,
                  "y":78},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u60.png"}},
{
          "id":"d76a65f3f24a4d38bee2bcad3950c167",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":783,
              "y":60},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea0c67e4d31b40b6935504be221595c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":783,
                  "y":60},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7554af41d4c941d89bd978fa94cf2a8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":218},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e038cf734b4449de806cfc501f10f949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":218},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ac1753b45d74f87ab5bad1529435fed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":236},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"778dcc4523dc4bfc89328e2a8b736943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":236},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"931276e26b7649598e29fe436f517489",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":336},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b0be1288ef7451dbb0f69a707e196c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":336},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22e41674d98546b091546b80daaf5f4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":354},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd475f56082e4d9fb83e342ddfc6e23d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":354},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9da2de85b734e9f8916128949a0e874",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":139},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f184fa04467a430a8e63c1f3c856a5ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":139},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"735b420cbcfb4948a38a1769f61e1c0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":255},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f516bbec9e846ea87660883e0abbdb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":255},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5e289493ba948a19284d1a46a1bfed2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":370},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243a019f0d8847ac8adc6ddb1f8c6543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":370},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cba6469bb1ff4bc5aa5fede825017cbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":336},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3d1566532ce46ca80a52ca4482c35ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":336},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"11000ed475fc4e1fa7a054c4a1086a07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":218},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"256291eb8db047f798067e08ae335e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":218},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"72126b1f8bc84b60b5ff30b7737fd341",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":102},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b52ff33ac6247c18e2acc9f9174f48c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":446,
                  "y":102},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"8d3652a920194755ba8dcc906a6c9563",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"50bcb3d7d887478bbf9f783007cef053",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":200,
              "height":383},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4339f71a000347789ec8e3a99ff894d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":200,
                  "height":383},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u120.png"}},
{
          "id":"6f79e9d4e508477bb8d10a605a40d62b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1094,
              "y":50},
            "size":{
              "width":10,
              "height":383},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/employee_dashboard/u122_line.png"}},
{
          "id":"da1a61bce0d742c09e95c9c55b6465f2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":644,
              "y":50},
            "size":{
              "width":10,
              "height":383},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/employee_dashboard/u122_line.png"}},
{
          "id":"acb430e5dd054df8b7d1e5d0bde4c80f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":102},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"80d481ea62194de798d67c7f8154b37f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":111}},
          "adaptiveStyles":{
},
          "masterId":"90f43170a91248b4b2b049d279a0d2a0"},
{
          "id":"550eb5cdc03046eeb39cd7961aed45c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":117},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37e9758946c44a5d9e30b45d10aa05aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":775,
                  "y":117},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u3.png"}},
{
          "id":"d807c24af3f54eb68b2bdcc80d065c89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":835,
              "y":117},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ae444d3f9184199a5d7193416f7eb40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":835,
                  "y":117},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99d0e3c606f24c6683c58ab7eb163c57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":906,
              "y":120},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"defc21a3d04c4d6b880a8dfe4c04e928",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":906,
                  "y":120},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"0a38d77d0f7b46a28d79bb11df4fe7fc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7960479542a744d09a89949d89357fee"}]}},
  "masters":{
    "cb2317a61a23419e8f00adf3082fa67c":{
      "packageId":"cb2317a61a23419e8f00adf3082fa67c",
      "type":"Axure:Master",
      "name":"Employee pattern",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"4110f2af98c14ef3919214cf5f1fee0b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":226,
                "height":66}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2982cbd279c649d09f3dc16a7ae45f5b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":226,
                    "height":66}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u1.png",
              "normal~":"images/employee_dashboard/u1.png",
              "normal~":"images/employee_dashboard/u1.png"}},
{
            "id":"45c5319c6c6544df8e8245cc4637e69f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":5,
                "y":6},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ce2dc9f657d14f75a385e5f9fa0f1eae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":5,
                    "y":6},
                  "size":{
                    "width":50,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u3.png",
              "normal~":"images/employee_dashboard/u3.png",
              "normal~":"images/employee_dashboard/u3.png"}},
{
            "id":"ee2429d9236543e2b59ba0bceb167b3d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":226,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ea175c4fd45946b2810d3778c56e17a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":226,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u5.png",
              "normal~":"images/employee_dashboard/u5.png",
              "normal~":"images/employee_dashboard/u5.png"}},
{
            "id":"44ce6f1d72ec476fad2c6f07b453960c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":162.5,
                "y":71},
              "size":{
                "width":52,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9d14d9fa3bb408a906816d10d389003",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":162.5,
                    "y":71},
                  "size":{
                    "width":52,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Employee (client view) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"employee__client_view_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/employee_dashboard/u7.png",
              "normal~":"images/employee_dashboard/u7.png",
              "normal~":"images/employee_dashboard/u7.png"}}]}},
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u130.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u132.png"}}]}},
    "90f43170a91248b4b2b049d279a0d2a0":{
      "packageId":"90f43170a91248b4b2b049d279a0d2a0",
      "type":"Axure:Master",
      "name":"Project pattern",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"38556c2f70314804a20a0754b7386c4f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":226,
                "height":66}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"812095211a414f0f92a1c5bb2a218acd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":226,
                    "height":66}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u1.png"}},
{
            "id":"f308d3e7f1694674b893d5fd8e40fe59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":226,
                "height":35}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"98d39b2aa2694e8e8fbfb2b14539a097",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":226,
                    "height":35}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u5.png"}},
{
            "id":"d3b8318974944ac382562757931c85b6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":162,
                "y":71},
              "size":{
                "width":52,
                "height":23}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d1741995a94d4a7f8d9dced26ab88ee1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":162,
                    "y":71},
                  "size":{
                    "width":52,
                    "height":23}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Project (client view) in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"project__client_view_.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/employee_dashboard/u7.png"}}]}},
    "7960479542a744d09a89949d89357fee":{
      "packageId":"7960479542a744d09a89949d89357fee",
      "type":"Axure:Master",
      "name":"Client menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c1c2bf7a73b142e98889e67c858f6199",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Client dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"client_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"532b2c922e8e4042a2f400488f29927e",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Client profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"client_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "e2e8779d8feb49cba67aabe2d1aca2f9":{
      "scriptId":"u0",
      "4110f2af98c14ef3919214cf5f1fee0b":{
        "scriptId":"u1"},
      "2982cbd279c649d09f3dc16a7ae45f5b":{
        "scriptId":"u2"},
      "45c5319c6c6544df8e8245cc4637e69f":{
        "scriptId":"u3"},
      "ce2dc9f657d14f75a385e5f9fa0f1eae":{
        "scriptId":"u4"},
      "ee2429d9236543e2b59ba0bceb167b3d":{
        "scriptId":"u5"},
      "ea175c4fd45946b2810d3778c56e17a5":{
        "scriptId":"u6"},
      "44ce6f1d72ec476fad2c6f07b453960c":{
        "scriptId":"u7"},
      "b9d14d9fa3bb408a906816d10d389003":{
        "scriptId":"u8"}},
    "f641ef2cb7e94f89b864a653cad8a0b4":{
      "scriptId":"u9",
      "4110f2af98c14ef3919214cf5f1fee0b":{
        "scriptId":"u10"},
      "2982cbd279c649d09f3dc16a7ae45f5b":{
        "scriptId":"u11"},
      "45c5319c6c6544df8e8245cc4637e69f":{
        "scriptId":"u12"},
      "ce2dc9f657d14f75a385e5f9fa0f1eae":{
        "scriptId":"u13"},
      "ee2429d9236543e2b59ba0bceb167b3d":{
        "scriptId":"u14"},
      "ea175c4fd45946b2810d3778c56e17a5":{
        "scriptId":"u15"},
      "44ce6f1d72ec476fad2c6f07b453960c":{
        "scriptId":"u16"},
      "b9d14d9fa3bb408a906816d10d389003":{
        "scriptId":"u17"}},
    "a89e78b631d04e30aa0db60dc5f04220":{
      "scriptId":"u18"},
    "cab9bee4c099415b9a7f2254a84126f6":{
      "scriptId":"u19"},
    "56e757cde87246d5b5d3d1f3661fe1c1":{
      "scriptId":"u20"},
    "3eab7f09c1b7423b95fe01cb95023d59":{
      "scriptId":"u21"},
    "98b3688aaa5749beb9721137bce71b78":{
      "scriptId":"u22",
      "4110f2af98c14ef3919214cf5f1fee0b":{
        "scriptId":"u23"},
      "2982cbd279c649d09f3dc16a7ae45f5b":{
        "scriptId":"u24"},
      "45c5319c6c6544df8e8245cc4637e69f":{
        "scriptId":"u25"},
      "ce2dc9f657d14f75a385e5f9fa0f1eae":{
        "scriptId":"u26"},
      "ee2429d9236543e2b59ba0bceb167b3d":{
        "scriptId":"u27"},
      "ea175c4fd45946b2810d3778c56e17a5":{
        "scriptId":"u28"},
      "44ce6f1d72ec476fad2c6f07b453960c":{
        "scriptId":"u29"},
      "b9d14d9fa3bb408a906816d10d389003":{
        "scriptId":"u30"}},
    "dfe4f464664a4d3aa19a3ee567153498":{
      "scriptId":"u31"},
    "e2612b685b42462aba51c43461405856":{
      "scriptId":"u32"},
    "fe71bf3dd1a3478aae12c8438cc5243b":{
      "scriptId":"u33"},
    "f95da6d7631b41158c69f1624e945d2a":{
      "scriptId":"u34"},
    "b61c3d5879f04d658e69916859e1fcab":{
      "scriptId":"u35"},
    "07f535a9c4aa4f1b8232e265a4c8276b":{
      "scriptId":"u36"},
    "deeb8b1a79454a2788684c6711b2dd0a":{
      "scriptId":"u37"},
    "04a3267c1fbe4bea93d6340c20b7824b":{
      "scriptId":"u38"},
    "1ca7d487cd284aa3bf57e3c534e454a5":{
      "scriptId":"u39"},
    "fb6d1059115845e488f7722f729ee239":{
      "scriptId":"u40"},
    "39ed9c37236b45b5b93e0e7f295c84f8":{
      "scriptId":"u41"},
    "60e81b4ea8784e009e10831e6ca5a247":{
      "scriptId":"u42"},
    "bbb422fcb63a4649b6905f8cc962dd3b":{
      "scriptId":"u43"},
    "f394823a325b4ebdaf76ec5d287b3774":{
      "scriptId":"u44"},
    "8c8c9c1be70f409dbfe55be5d87c31ec":{
      "scriptId":"u45"},
    "7a651bb02d5a48dc8e392951e7338052":{
      "scriptId":"u46"},
    "c71c3b4bfe134fdfa21d29412e820266":{
      "scriptId":"u47"},
    "af73a8f7508c4d6a8b2ddd9b0429985c":{
      "scriptId":"u48"},
    "ce04d4203a224a0092ed5044b9269015":{
      "scriptId":"u49"},
    "f06786e5a60340de90d641ca5628864f":{
      "scriptId":"u50"},
    "383f6a7174d54014bd32047db89a48ac":{
      "scriptId":"u51"},
    "b1fbdab57f6a4c0989cbe17209e95f6a":{
      "scriptId":"u52"},
    "1e76c5bf78804b818123061f15ced10f":{
      "scriptId":"u53"},
    "a073b8d269f048798c2caac11e1409fd":{
      "scriptId":"u54"},
    "671ea9f5bb97473cbb66b9d2bcd81c3d":{
      "scriptId":"u55"},
    "3ac4f5025552452fa791d5fc385d2347":{
      "scriptId":"u56"},
    "b603e1c0e5c04344912e83e834a0fb9d":{
      "scriptId":"u57"},
    "56ba62a3543443499dd1f82b800cdbab":{
      "scriptId":"u58"},
    "0a9d25d921ce414187086ee455044875":{
      "scriptId":"u59"},
    "b4387bc4caf04dc5b88856f691595072":{
      "scriptId":"u60"},
    "41aebad040454a29b99c709f85c043bb":{
      "scriptId":"u61"},
    "c51c4d2ea1d940919081d34debc91fd2":{
      "scriptId":"u62"},
    "2e102b37d61c4ef693ebf2ec6b05e564":{
      "scriptId":"u63"},
    "b7278df09c8d4829a3dc3dea52a21544":{
      "scriptId":"u64"},
    "c118b87609b44a08acf2f43c21fe259a":{
      "scriptId":"u65"},
    "f6b4bd2a8cc749c58588b066833a29f6":{
      "scriptId":"u66"},
    "1dddfd69d0d64735be80b1157b4fee6a":{
      "scriptId":"u67"},
    "1d420c54f0e843059f474ddbd93e0469":{
      "scriptId":"u68"},
    "1a31f59e09484de88e9b8434dcb9e875":{
      "scriptId":"u69"},
    "4868105572bd483e9c3d62f4bb8b35d9":{
      "scriptId":"u70"},
    "a5072597d27f458c8b81a55310825271":{
      "scriptId":"u71"},
    "977c7db61e614f77a274d396e57a83b9":{
      "scriptId":"u72"},
    "9aaa058d023d45bf93b714f3ae99d28e":{
      "scriptId":"u73"},
    "1716bea8727845cb958b1c0aa6df8d03":{
      "scriptId":"u74"},
    "fa2de2bff6a84e53a6fae9d25d7287d4":{
      "scriptId":"u75"},
    "0ec0e9f97ba04d7e93d1358635d93c56":{
      "scriptId":"u76"},
    "bb73ffa65e7044549f3ce32627d3b07c":{
      "scriptId":"u77"},
    "04b334e0d0684a2f8898bedfe4d7fb5f":{
      "scriptId":"u78"},
    "33c45907761e4958a8034be915f4e25c":{
      "scriptId":"u79"},
    "87a923daadad418bb6b9de6b0f10760e":{
      "scriptId":"u80"},
    "5ec6ba8e689e401a80b19c78d8075c0b":{
      "scriptId":"u81"},
    "64a9ec669eee474e941bef2dc2b637fb":{
      "scriptId":"u82"},
    "dffbe8e3fb184974b982a55252e5f770":{
      "scriptId":"u83"},
    "d7b7923a6c8a44148a0aa0806a2d3be8":{
      "scriptId":"u84"},
    "ce96c65b85404492b12348393cafce37":{
      "scriptId":"u85"},
    "a3b073ee6fec422189c14b087cb8ee10":{
      "scriptId":"u86"},
    "233b5f5861b340aca611a33235bb71f0":{
      "scriptId":"u87"},
    "f807e224a8194c48bfcdca2fb923b2a4":{
      "scriptId":"u88"},
    "d76a65f3f24a4d38bee2bcad3950c167":{
      "scriptId":"u89"},
    "ea0c67e4d31b40b6935504be221595c8":{
      "scriptId":"u90"},
    "7554af41d4c941d89bd978fa94cf2a8f":{
      "scriptId":"u91"},
    "e038cf734b4449de806cfc501f10f949":{
      "scriptId":"u92"},
    "6ac1753b45d74f87ab5bad1529435fed":{
      "scriptId":"u93"},
    "778dcc4523dc4bfc89328e2a8b736943":{
      "scriptId":"u94"},
    "931276e26b7649598e29fe436f517489":{
      "scriptId":"u95"},
    "5b0be1288ef7451dbb0f69a707e196c3":{
      "scriptId":"u96"},
    "22e41674d98546b091546b80daaf5f4e":{
      "scriptId":"u97"},
    "bd475f56082e4d9fb83e342ddfc6e23d":{
      "scriptId":"u98"},
    "b9da2de85b734e9f8916128949a0e874":{
      "scriptId":"u99"},
    "f184fa04467a430a8e63c1f3c856a5ca":{
      "scriptId":"u100"},
    "735b420cbcfb4948a38a1769f61e1c0c":{
      "scriptId":"u101"},
    "8f516bbec9e846ea87660883e0abbdb5":{
      "scriptId":"u102"},
    "b5e289493ba948a19284d1a46a1bfed2":{
      "scriptId":"u103"},
    "243a019f0d8847ac8adc6ddb1f8c6543":{
      "scriptId":"u104"},
    "cba6469bb1ff4bc5aa5fede825017cbe":{
      "scriptId":"u105"},
    "a3d1566532ce46ca80a52ca4482c35ab":{
      "scriptId":"u106"},
    "11000ed475fc4e1fa7a054c4a1086a07":{
      "scriptId":"u107"},
    "256291eb8db047f798067e08ae335e5c":{
      "scriptId":"u108"},
    "72126b1f8bc84b60b5ff30b7737fd341":{
      "scriptId":"u109"},
    "6b52ff33ac6247c18e2acc9f9174f48c":{
      "scriptId":"u110"},
    "8d3652a920194755ba8dcc906a6c9563":{
      "scriptId":"u111",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u112"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u113"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u114"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u115"}},
    "50bcb3d7d887478bbf9f783007cef053":{
      "scriptId":"u116"},
    "4339f71a000347789ec8e3a99ff894d2":{
      "scriptId":"u117"},
    "6f79e9d4e508477bb8d10a605a40d62b":{
      "scriptId":"u118"},
    "da1a61bce0d742c09e95c9c55b6465f2":{
      "scriptId":"u119"},
    "acb430e5dd054df8b7d1e5d0bde4c80f":{
      "scriptId":"u120"},
    "80d481ea62194de798d67c7f8154b37f":{
      "scriptId":"u121",
      "38556c2f70314804a20a0754b7386c4f":{
        "scriptId":"u122"},
      "812095211a414f0f92a1c5bb2a218acd":{
        "scriptId":"u123"},
      "f308d3e7f1694674b893d5fd8e40fe59":{
        "scriptId":"u124"},
      "98d39b2aa2694e8e8fbfb2b14539a097":{
        "scriptId":"u125"},
      "d3b8318974944ac382562757931c85b6":{
        "scriptId":"u126"},
      "d1741995a94d4a7f8d9dced26ab88ee1":{
        "scriptId":"u127"}},
    "550eb5cdc03046eeb39cd7961aed45c2":{
      "scriptId":"u128"},
    "37e9758946c44a5d9e30b45d10aa05aa":{
      "scriptId":"u129"},
    "d807c24af3f54eb68b2bdcc80d065c89":{
      "scriptId":"u130"},
    "8ae444d3f9184199a5d7193416f7eb40":{
      "scriptId":"u131"},
    "99d0e3c606f24c6683c58ab7eb163c57":{
      "scriptId":"u132"},
    "defc21a3d04c4d6b880a8dfe4c04e928":{
      "scriptId":"u133"},
    "0a38d77d0f7b46a28d79bb11df4fe7fc":{
      "scriptId":"u134",
      "c1c2bf7a73b142e98889e67c858f6199":{
        "scriptId":"u135"},
      "532b2c922e8e4042a2f400488f29927e":{
        "scriptId":"u136"}}}});