$axure.loadCurrentPage({
  "url":"manager_board.html",
  "generationDate":new Date(1439391546844.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9441f3fe51144bbd8de08571aa14368b",
    "type":"Axure:Page",
    "name":"Manager board",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c5a1fced55c548deb17847865a50599f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":200,
              "height":429},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b14529ec8234fec89f15dffec66cede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":200,
                  "height":429},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/manager_board/u0.png"}},
{
          "id":"7c9939431fe04219aa8a63761e137e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":398,
              "y":74},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ffbe10840ae4d20848972d57a02bc9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":398,
                  "y":74},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"dbcc750432be4a7e8b146fa9feb99d6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":401,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9803260bd5cd43ef9f59cfc464bdb7a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":401,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"7ba6dca658644cbc98ad8f41c40132b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":407,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73aaa790fae14989abd4ed6b92594933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":407,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"1d37eaec4d8240af80d8a3d340b76e95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":414,
              "y":76},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95b169c6c84541648f453c62c708067d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":414,
                  "y":76},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"e9cf609daa0f49cfab957922a5a091ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":401,
              "y":82},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08164b67eff14861a4bf9f1db3e5a769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":401,
                  "y":82},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"7bc04e84120940158e8cfb32c961e0b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":407,
              "y":82},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36e1a37542c343279affeb790359d100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":407,
                  "y":82},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"2c168db102a8479eb8652bd5662a40ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":414,
              "y":82},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e915fdad6f534606a308748448788900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":414,
                  "y":82},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"d510b2618a4f4e82b1fa2661b6a53b05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":401,
              "y":88},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12c2db3f5f6346ec95fae36a50767194",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":401,
                  "y":88},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"96d528eba6e94ff088faa3487f33c2be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":407,
              "y":88},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c59c5fa7aeae4204a0fedf7fa3e5ced6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":407,
                  "y":88},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"7b70223fe27f44c1b712441b3b8ca96b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":414,
              "y":88},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20acfee634f9441fb7c2031b5af0221f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":414,
                  "y":88},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"d3c9a3e63d8e430ea28ec48dc6291804",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":437,
              "y":74},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad77204234624e41a24eb9947a1e6880",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":437,
                  "y":74},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"3edc46eb28984f2fa3d26bcbe1472643",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":439,
              "y":76},
            "size":{
              "width":19,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ea153fee2b44d269795b099bd31f3fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":439,
                  "y":76},
                "size":{
                  "width":19,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u22.png"}},
{
          "id":"fbe9db2b5c7a46ccbb1add269a42e4be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":439,
              "y":82},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11205017f5fe471baf7a1d92e452d30f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":439,
                  "y":82},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u24.png"}},
{
          "id":"ce66cefd8ac8453d857f6db4c3d79d60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":439,
              "y":88},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b09e78218f6f4674914ebad0938b0d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":439,
                  "y":88},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u24.png"}},
{
          "id":"b957603bb94a4ccda97d75c0719904a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":118},
            "size":{
              "width":226,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2ce9c6ae71044cda930e7cbcc3cd24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":118},
                "size":{
                  "width":226,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u28.png"}},
{
          "id":"28bcc5424106487dad8218a85235127b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":124},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e948604071d4ce6b51f24525c0a66e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":124},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u30.png"}},
{
          "id":"26d193fe18cb473ab0c80f0439d4bf18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":124},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"803ad979ccc140b1ab03505a2381d1eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":124},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b193a093fdf047dfa2fac11eae0e0d26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":142},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bb8f734782d4c7587ea7a4e1adf9b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":142},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92b76bba12464694976c1622006c37dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":234,
              "y":184},
            "size":{
              "width":226,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f86e9933624abe9416bf35f1fbb1e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":234,
                  "y":184},
                "size":{
                  "width":226,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u36.png"}},
{
          "id":"37a31d8738ec4619add73dee770ceddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":190},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63c269d2d170476ca870c70fc15d1ea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":345,
                  "y":190},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"615e093aab4f4800957a16a482e04396",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":190},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"230b00039d8d47d684a5e17edff1a026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":402,
                  "y":190},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"129ae38a681a4ce78336eb04b0ed6f31",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":243,
              "y":72},
            "size":{
              "width":104,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34dc3d360f8b4cdc85196e8da8e40aad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":243,
                  "y":72},
                "size":{
                  "width":104,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c401d686cf5f429b968cba94d3a24d21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":703,
              "y":78},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db39358130744503a8408d6a638b1888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":703,
                  "y":78},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"da4b13fe47c540d6890fe9b9856f377b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":706,
              "y":80},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67d12abebcca4df7aced3a9d3496c325",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":706,
                  "y":80},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"ed36bd96c6f144ae9f2537977636739e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":712,
              "y":80},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f979a85c9b0245ceb96ffca995d07c60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":712,
                  "y":80},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"243eccb9de6f4d768371d039d8c23ea3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":719,
              "y":80},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdd0505218d04386891ea8f12d53fb7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":719,
                  "y":80},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"d1892e17085c4dca8b97edf41cb2cc51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":706,
              "y":86},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c9437eeaef2413c9d0674b15b249471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":706,
                  "y":86},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"4054acaec7d24b56a1d01ac2e0d0a3dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":712,
              "y":86},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f1f929bc27a425bb790968603cf23a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":712,
                  "y":86},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"ac640f9850474b74ab87b63fe9f37a2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":719,
              "y":86},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8040883a8e1416aadeea194b180dde3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":719,
                  "y":86},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"43cc1c4f1bba409bac11558708dd4d75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":706,
              "y":92},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"900dbb408e36446e870f74e798e4bcfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":706,
                  "y":92},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"698310120b374244bab1576fbab38b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":712,
              "y":92},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b5e6a0e370242f39b4933d94aefce83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":712,
                  "y":92},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"5a44034c27e5451fb8e5a6c288cf40d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":719,
              "y":92},
            "size":{
              "width":4,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0270e03edd74366b83d5db94d77c6bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":719,
                  "y":92},
                "size":{
                  "width":4,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"a2d643a83db740ffa938cc966acc6794",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":742,
              "y":78},
            "size":{
              "width":23,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f05ad5fb5d41c08c24035ad187bac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":742,
                  "y":78},
                "size":{
                  "width":23,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"60cb2237e85b4283b31167ae48c4e703",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":744,
              "y":81},
            "size":{
              "width":19,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86109412e4a942d5b847063d2396e745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":744,
                  "y":81},
                "size":{
                  "width":19,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u22.png"}},
{
          "id":"7b96bb6bfb134da39af937b4d9665260",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":744,
              "y":87},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e827feb19f5d4cc597ae5dac48a8a24c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":744,
                  "y":87},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u24.png"}},
{
          "id":"21b8801ef8714922ae64fc34839a85b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":744,
              "y":92},
            "size":{
              "width":19,
              "height":3},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9b754fea1c24d16b926c190a0cca848",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":744,
                  "y":92},
                "size":{
                  "width":19,
                  "height":3},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u24.png"}},
{
          "id":"944cfec668854dd6bf2f106339c33da2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":552,
              "y":74},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4e3f09149db47f2943634a8c2ded97e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":552,
                  "y":74},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f3efefe332149fa92ed1218e9e561fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":190},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93cf457c27d847aba566fa671796b145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":190},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"cbe306796e0641a58e281c86dde149b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":234},
            "size":{
              "width":226,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfb95ebfebc2477a84ad3209caf24a9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":234},
                "size":{
                  "width":226,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u28.png"}},
{
          "id":"336b92cfbab241ca897264040e967a75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":240},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42225915f5ab404c97491e9457249512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":240},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u30.png"}},
{
          "id":"1a4926b48ec94af19c4d4284e92c8408",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":240},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bec1da3e3704d7098abaf9b7e13477d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":240},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"494dde27f8b745249507300d58a0fec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":258},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49841f40b086405388a656b90ab31a0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":258},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3110c136873f48dd9e451d0b054fa4dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":234,
              "y":300},
            "size":{
              "width":226,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de5b43e7840340f3810ff1be0414340c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":234,
                  "y":300},
                "size":{
                  "width":226,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u36.png"}},
{
          "id":"eb4739956a594cb8aed5746b84900b18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":306},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c25161e648484a5b88377967f900e860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":345,
                  "y":306},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"d3f31bb220d84e9581a872d75a09daad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":306},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e071f2f952ae4aca9fbf4f0da5232cb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":402,
                  "y":306},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"6528472a60434db7bf3552c56a26aa0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":306},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a97684963bf44d40979cccd96dbdef74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":306},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"3492c4055ad241aeb657b59df12d3c02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":354},
            "size":{
              "width":226,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deca2cf49b3c4d0ea0f763e1dd072319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":354},
                "size":{
                  "width":226,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u28.png"}},
{
          "id":"569ac1d5389845fa9c37c1a4921c60d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":360},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7475a06481fa487f866ccd50a12cb61d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":360},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u30.png"}},
{
          "id":"b1bdafcdea6a4d8c8177da956eafdc60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":360},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e2693567cd041599ea6836fa0a96404",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":360},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"729e952a9d5543309e315b9463646b7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":378},
            "size":{
              "width":93,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03ba8c7eeed345b7acd3e855c8f6d47a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":378},
                "size":{
                  "width":93,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37e56a4b9aca42c79442f952747602ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":234,
              "y":420},
            "size":{
              "width":226,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d7c8b39a7214562b3b5e426b505c7ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":234,
                  "y":420},
                "size":{
                  "width":226,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u36.png"}},
{
          "id":"25d36c8712cf4e2eae53cd9375b6e6ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":426},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23e865ef91004c52a2ba5c848d40f828",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":345,
                  "y":426},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"6f737e59ae0a48249ce1882b68dfd023",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":402,
              "y":426},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef59deedf2bd43b7a3dd6f8b5d4cdf0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":402,
                  "y":426},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"0612684515f946d0a60b15871d23ad90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":426},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a399b0e6b87f43eebc42302185695f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":426},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"105cfb3c49aa4403b5c850065557d01e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":121},
            "size":{
              "width":226,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88606a5d6d1f453db15a0a5f04bbb6b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":539,
                  "y":121},
                "size":{
                  "width":226,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u28.png"}},
{
          "id":"1d984dfc411f41eead0f2af84b39c47e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":544,
              "y":127},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bfdb856055d4f1ab23fd9b3f9ac403e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":544,
                  "y":127},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u30.png"}},
{
          "id":"da689fc6dfce4b3bba2244d784b0b4cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":126},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1596fbf605d49d48bf1d3b377ac13c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":126},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e87d5e2d3536497686f009a3da00d0d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":539,
              "y":186},
            "size":{
              "width":226,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcc0be90d23d407cb7f6d0bef3ea7813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":539,
                  "y":186},
                "size":{
                  "width":226,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u36.png"}},
{
          "id":"c4679c782c5149558b3703759672a4b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":192},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2694be235a1436ea5a8c3b20967bc2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":192},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"402999adcdfa4b79b829c71f572fa645",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":707,
              "y":192},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a339798f9e74efe9e271b59465af467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":707,
                  "y":192},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"6ad31d7e44214e32af53fa3ecb431c41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":192},
            "size":{
              "width":52,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"518ff7383d5c4764885ca4a301dc05d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":192},
                "size":{
                  "width":52,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.png"}},
{
          "id":"39be860b7d9d4318b0f9aafe40bfd42d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":160},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd0ff2b783844e2ae38d0d2649ca79f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":160},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22545bd848e14f1aa5750e6a74dd8454",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":276},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1509f0deb87c41398ba045892f4e8526",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":276},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bc463d5ea3146ce8c0ba09dca92e148",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":394},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5dbb2d121eb45f5801149fc1af67b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":394},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88234d8cc72347c0bc75a070cb290762",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":360},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91556c0f011147a49c5cdbfb52456d5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":360},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u172.png"}},
{
          "id":"02847fd55004469b949ace8227b35137",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":381,
              "y":240},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bafcb46c9964d25a6e7a20a12b97eb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":381,
                  "y":240},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u172.png"}},
{
          "id":"5034589c2e4c42d4b4a46e90dff0240e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":124},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2f3484cc1ec48e8b0d042ef37d3f7af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":124},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u172.png"}},
{
          "id":"7080fdc8fcf0422fadc7ed8db0e3c4f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":129},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ab2f766bdc47ad8b6ea8d81bec4538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":129},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u172.png"}},
{
          "id":"dfc0c6cd4c93410b9b2a6ad19840b783",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c638043f37fa4790bc2677cba10deb0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":800,
              "y":48},
            "size":{
              "width":200,
              "height":431},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72704fb0f7c8441483cb74b9a0f08226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":800,
                  "y":48},
                "size":{
                  "width":200,
                  "height":431},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/manager_board/u139.png"}},
{
          "id":"2b1dfa981b774702b9af12cb4c6d1bc2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":21},
            "size":{
              "width":10,
              "height":458}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/manager_board/u141_line.png"}},
{
          "id":"125c102c1b684adc8ad536cd6cdeb8a4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u195.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u197.png"}}]}}},
  "objectPaths":{
    "c5a1fced55c548deb17847865a50599f":{
      "scriptId":"u0"},
    "0b14529ec8234fec89f15dffec66cede":{
      "scriptId":"u1"},
    "7c9939431fe04219aa8a63761e137e37":{
      "scriptId":"u2"},
    "1ffbe10840ae4d20848972d57a02bc9e":{
      "scriptId":"u3"},
    "dbcc750432be4a7e8b146fa9feb99d6f":{
      "scriptId":"u4"},
    "9803260bd5cd43ef9f59cfc464bdb7a9":{
      "scriptId":"u5"},
    "7ba6dca658644cbc98ad8f41c40132b6":{
      "scriptId":"u6"},
    "73aaa790fae14989abd4ed6b92594933":{
      "scriptId":"u7"},
    "1d37eaec4d8240af80d8a3d340b76e95":{
      "scriptId":"u8"},
    "95b169c6c84541648f453c62c708067d":{
      "scriptId":"u9"},
    "e9cf609daa0f49cfab957922a5a091ba":{
      "scriptId":"u10"},
    "08164b67eff14861a4bf9f1db3e5a769":{
      "scriptId":"u11"},
    "7bc04e84120940158e8cfb32c961e0b6":{
      "scriptId":"u12"},
    "36e1a37542c343279affeb790359d100":{
      "scriptId":"u13"},
    "2c168db102a8479eb8652bd5662a40ef":{
      "scriptId":"u14"},
    "e915fdad6f534606a308748448788900":{
      "scriptId":"u15"},
    "d510b2618a4f4e82b1fa2661b6a53b05":{
      "scriptId":"u16"},
    "12c2db3f5f6346ec95fae36a50767194":{
      "scriptId":"u17"},
    "96d528eba6e94ff088faa3487f33c2be":{
      "scriptId":"u18"},
    "c59c5fa7aeae4204a0fedf7fa3e5ced6":{
      "scriptId":"u19"},
    "7b70223fe27f44c1b712441b3b8ca96b":{
      "scriptId":"u20"},
    "20acfee634f9441fb7c2031b5af0221f":{
      "scriptId":"u21"},
    "d3c9a3e63d8e430ea28ec48dc6291804":{
      "scriptId":"u22"},
    "ad77204234624e41a24eb9947a1e6880":{
      "scriptId":"u23"},
    "3edc46eb28984f2fa3d26bcbe1472643":{
      "scriptId":"u24"},
    "1ea153fee2b44d269795b099bd31f3fa":{
      "scriptId":"u25"},
    "fbe9db2b5c7a46ccbb1add269a42e4be":{
      "scriptId":"u26"},
    "11205017f5fe471baf7a1d92e452d30f":{
      "scriptId":"u27"},
    "ce66cefd8ac8453d857f6db4c3d79d60":{
      "scriptId":"u28"},
    "b09e78218f6f4674914ebad0938b0d8d":{
      "scriptId":"u29"},
    "b957603bb94a4ccda97d75c0719904a5":{
      "scriptId":"u30"},
    "a2ce9c6ae71044cda930e7cbcc3cd24e":{
      "scriptId":"u31"},
    "28bcc5424106487dad8218a85235127b":{
      "scriptId":"u32"},
    "5e948604071d4ce6b51f24525c0a66e3":{
      "scriptId":"u33"},
    "26d193fe18cb473ab0c80f0439d4bf18":{
      "scriptId":"u34"},
    "803ad979ccc140b1ab03505a2381d1eb":{
      "scriptId":"u35"},
    "b193a093fdf047dfa2fac11eae0e0d26":{
      "scriptId":"u36"},
    "8bb8f734782d4c7587ea7a4e1adf9b08":{
      "scriptId":"u37"},
    "92b76bba12464694976c1622006c37dd":{
      "scriptId":"u38"},
    "96f86e9933624abe9416bf35f1fbb1e2":{
      "scriptId":"u39"},
    "37a31d8738ec4619add73dee770ceddd":{
      "scriptId":"u40"},
    "63c269d2d170476ca870c70fc15d1ea8":{
      "scriptId":"u41"},
    "615e093aab4f4800957a16a482e04396":{
      "scriptId":"u42"},
    "230b00039d8d47d684a5e17edff1a026":{
      "scriptId":"u43"},
    "129ae38a681a4ce78336eb04b0ed6f31":{
      "scriptId":"u44"},
    "34dc3d360f8b4cdc85196e8da8e40aad":{
      "scriptId":"u45"},
    "c401d686cf5f429b968cba94d3a24d21":{
      "scriptId":"u46"},
    "db39358130744503a8408d6a638b1888":{
      "scriptId":"u47"},
    "da4b13fe47c540d6890fe9b9856f377b":{
      "scriptId":"u48"},
    "67d12abebcca4df7aced3a9d3496c325":{
      "scriptId":"u49"},
    "ed36bd96c6f144ae9f2537977636739e":{
      "scriptId":"u50"},
    "f979a85c9b0245ceb96ffca995d07c60":{
      "scriptId":"u51"},
    "243eccb9de6f4d768371d039d8c23ea3":{
      "scriptId":"u52"},
    "fdd0505218d04386891ea8f12d53fb7e":{
      "scriptId":"u53"},
    "d1892e17085c4dca8b97edf41cb2cc51":{
      "scriptId":"u54"},
    "7c9437eeaef2413c9d0674b15b249471":{
      "scriptId":"u55"},
    "4054acaec7d24b56a1d01ac2e0d0a3dd":{
      "scriptId":"u56"},
    "9f1f929bc27a425bb790968603cf23a0":{
      "scriptId":"u57"},
    "ac640f9850474b74ab87b63fe9f37a2a":{
      "scriptId":"u58"},
    "f8040883a8e1416aadeea194b180dde3":{
      "scriptId":"u59"},
    "43cc1c4f1bba409bac11558708dd4d75":{
      "scriptId":"u60"},
    "900dbb408e36446e870f74e798e4bcfd":{
      "scriptId":"u61"},
    "698310120b374244bab1576fbab38b3c":{
      "scriptId":"u62"},
    "7b5e6a0e370242f39b4933d94aefce83":{
      "scriptId":"u63"},
    "5a44034c27e5451fb8e5a6c288cf40d5":{
      "scriptId":"u64"},
    "f0270e03edd74366b83d5db94d77c6bb":{
      "scriptId":"u65"},
    "a2d643a83db740ffa938cc966acc6794":{
      "scriptId":"u66"},
    "f5f05ad5fb5d41c08c24035ad187bac2":{
      "scriptId":"u67"},
    "60cb2237e85b4283b31167ae48c4e703":{
      "scriptId":"u68"},
    "86109412e4a942d5b847063d2396e745":{
      "scriptId":"u69"},
    "7b96bb6bfb134da39af937b4d9665260":{
      "scriptId":"u70"},
    "e827feb19f5d4cc597ae5dac48a8a24c":{
      "scriptId":"u71"},
    "21b8801ef8714922ae64fc34839a85b8":{
      "scriptId":"u72"},
    "a9b754fea1c24d16b926c190a0cca848":{
      "scriptId":"u73"},
    "944cfec668854dd6bf2f106339c33da2":{
      "scriptId":"u74"},
    "d4e3f09149db47f2943634a8c2ded97e":{
      "scriptId":"u75"},
    "4f3efefe332149fa92ed1218e9e561fa":{
      "scriptId":"u76"},
    "93cf457c27d847aba566fa671796b145":{
      "scriptId":"u77"},
    "cbe306796e0641a58e281c86dde149b3":{
      "scriptId":"u78"},
    "cfb95ebfebc2477a84ad3209caf24a9c":{
      "scriptId":"u79"},
    "336b92cfbab241ca897264040e967a75":{
      "scriptId":"u80"},
    "42225915f5ab404c97491e9457249512":{
      "scriptId":"u81"},
    "1a4926b48ec94af19c4d4284e92c8408":{
      "scriptId":"u82"},
    "1bec1da3e3704d7098abaf9b7e13477d":{
      "scriptId":"u83"},
    "494dde27f8b745249507300d58a0fec1":{
      "scriptId":"u84"},
    "49841f40b086405388a656b90ab31a0b":{
      "scriptId":"u85"},
    "3110c136873f48dd9e451d0b054fa4dc":{
      "scriptId":"u86"},
    "de5b43e7840340f3810ff1be0414340c":{
      "scriptId":"u87"},
    "eb4739956a594cb8aed5746b84900b18":{
      "scriptId":"u88"},
    "c25161e648484a5b88377967f900e860":{
      "scriptId":"u89"},
    "d3f31bb220d84e9581a872d75a09daad":{
      "scriptId":"u90"},
    "e071f2f952ae4aca9fbf4f0da5232cb4":{
      "scriptId":"u91"},
    "6528472a60434db7bf3552c56a26aa0b":{
      "scriptId":"u92"},
    "a97684963bf44d40979cccd96dbdef74":{
      "scriptId":"u93"},
    "3492c4055ad241aeb657b59df12d3c02":{
      "scriptId":"u94"},
    "deca2cf49b3c4d0ea0f763e1dd072319":{
      "scriptId":"u95"},
    "569ac1d5389845fa9c37c1a4921c60d5":{
      "scriptId":"u96"},
    "7475a06481fa487f866ccd50a12cb61d":{
      "scriptId":"u97"},
    "b1bdafcdea6a4d8c8177da956eafdc60":{
      "scriptId":"u98"},
    "3e2693567cd041599ea6836fa0a96404":{
      "scriptId":"u99"},
    "729e952a9d5543309e315b9463646b7e":{
      "scriptId":"u100"},
    "03ba8c7eeed345b7acd3e855c8f6d47a":{
      "scriptId":"u101"},
    "37e56a4b9aca42c79442f952747602ab":{
      "scriptId":"u102"},
    "5d7c8b39a7214562b3b5e426b505c7ba":{
      "scriptId":"u103"},
    "25d36c8712cf4e2eae53cd9375b6e6ee":{
      "scriptId":"u104"},
    "23e865ef91004c52a2ba5c848d40f828":{
      "scriptId":"u105"},
    "6f737e59ae0a48249ce1882b68dfd023":{
      "scriptId":"u106"},
    "ef59deedf2bd43b7a3dd6f8b5d4cdf0f":{
      "scriptId":"u107"},
    "0612684515f946d0a60b15871d23ad90":{
      "scriptId":"u108"},
    "a399b0e6b87f43eebc42302185695f48":{
      "scriptId":"u109"},
    "105cfb3c49aa4403b5c850065557d01e":{
      "scriptId":"u110"},
    "88606a5d6d1f453db15a0a5f04bbb6b5":{
      "scriptId":"u111"},
    "1d984dfc411f41eead0f2af84b39c47e":{
      "scriptId":"u112"},
    "9bfdb856055d4f1ab23fd9b3f9ac403e":{
      "scriptId":"u113"},
    "da689fc6dfce4b3bba2244d784b0b4cd":{
      "scriptId":"u114"},
    "d1596fbf605d49d48bf1d3b377ac13c3":{
      "scriptId":"u115"},
    "e87d5e2d3536497686f009a3da00d0d3":{
      "scriptId":"u116"},
    "fcc0be90d23d407cb7f6d0bef3ea7813":{
      "scriptId":"u117"},
    "c4679c782c5149558b3703759672a4b0":{
      "scriptId":"u118"},
    "e2694be235a1436ea5a8c3b20967bc2a":{
      "scriptId":"u119"},
    "402999adcdfa4b79b829c71f572fa645":{
      "scriptId":"u120"},
    "4a339798f9e74efe9e271b59465af467":{
      "scriptId":"u121"},
    "6ad31d7e44214e32af53fa3ecb431c41":{
      "scriptId":"u122"},
    "518ff7383d5c4764885ca4a301dc05d0":{
      "scriptId":"u123"},
    "39be860b7d9d4318b0f9aafe40bfd42d":{
      "scriptId":"u124"},
    "4fd0ff2b783844e2ae38d0d2649ca79f":{
      "scriptId":"u125"},
    "22545bd848e14f1aa5750e6a74dd8454":{
      "scriptId":"u126"},
    "1509f0deb87c41398ba045892f4e8526":{
      "scriptId":"u127"},
    "3bc463d5ea3146ce8c0ba09dca92e148":{
      "scriptId":"u128"},
    "f5dbb2d121eb45f5801149fc1af67b7c":{
      "scriptId":"u129"},
    "88234d8cc72347c0bc75a070cb290762":{
      "scriptId":"u130"},
    "91556c0f011147a49c5cdbfb52456d5c":{
      "scriptId":"u131"},
    "02847fd55004469b949ace8227b35137":{
      "scriptId":"u132"},
    "6bafcb46c9964d25a6e7a20a12b97eb8":{
      "scriptId":"u133"},
    "5034589c2e4c42d4b4a46e90dff0240e":{
      "scriptId":"u134"},
    "e2f3484cc1ec48e8b0d042ef37d3f7af":{
      "scriptId":"u135"},
    "7080fdc8fcf0422fadc7ed8db0e3c4f5":{
      "scriptId":"u136"},
    "76ab2f766bdc47ad8b6ea8d81bec4538":{
      "scriptId":"u137"},
    "dfc0c6cd4c93410b9b2a6ad19840b783":{
      "scriptId":"u138"},
    "c638043f37fa4790bc2677cba10deb0c":{
      "scriptId":"u139"},
    "72704fb0f7c8441483cb74b9a0f08226":{
      "scriptId":"u140"},
    "2b1dfa981b774702b9af12cb4c6d1bc2":{
      "scriptId":"u141"},
    "125c102c1b684adc8ad536cd6cdeb8a4":{
      "scriptId":"u142",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u143"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u144"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u145"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u146"}}}});