$axure.loadCurrentPage({
  "url":"employee_profile.html",
  "generationDate":new Date(1439394925971.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"757d51d3738644b4b138fea27a565448",
    "type":"Axure:Page",
    "name":"Employee profile",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1dd4ded34226424d89b58495c8cae9b5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"07fe86b217d14de18fc7ec21783cb4f5"},
{
          "id":"faa47a1a0f8c4221b120081303e2cd2c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"c3d56b8804094e519836cba4ec98aa37"},
{
          "id":"8ad43dcc6f6440aeb5f29dbd7964d599",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1100,
              "height":1080},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8b1e998dfd84695a24e431e8bcb151e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1100,
                  "height":1080},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u8.png"}},
{
          "id":"b262d1cec5b84b41b97e9dba7233082c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":70},
            "size":{
              "width":120,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30d1b642f02e44f084cb8a333866bfe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":70},
                "size":{
                  "width":120,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u10.png"}},
{
          "id":"93517ea2c54e4f2884ca36d519f0ba08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":70},
            "size":{
              "width":93,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"defc914c5cd74008af01100ff26b1927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":70},
                "size":{
                  "width":93,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d08321a24f86425f998659d03949e9d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":146},
            "size":{
              "width":152,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c933431a8364f01b6e1f699f387e7c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":146},
                "size":{
                  "width":152,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a60023323464f9d89929a7fb8018e4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":243},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"303fae153dfe40dd987afbec9fc982de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":243},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7641296398f4876bcc69015c8d94668",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":213},
            "size":{
              "width":98,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fcfe4baf2b14ab6935ac60c66fc2416",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":213},
                "size":{
                  "width":98,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd423602cfe54806b6fc5797b51ac012",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":271},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d86f7df5fd3c46338479700eaf316563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":271},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a5a935acf37425bbfc26c34ee87fdf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":484},
            "size":{
              "width":79,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5835bc79141147c5ae74871f1f52687f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":484},
                "size":{
                  "width":79,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"620d83b0379343129d22ed9178e27533",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":518},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b3b0cc79a2241159e51c6a2ea86ed12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":518},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"5e7779ee83424959ac3b72ed4df0910a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":525},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"134ca627495d444b9f381adaa1507560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":525},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f608f13663a4c8fb2395fb9ca8f3e72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":556},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75231a2587da46248db4c710c949c813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":556},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f573c1efc899459ba6ff3b1c2867c707",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":590},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"812609d026df46daa6b87920da09134c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":590},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"503d360423b440e2a8aa9948953ca6a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":327,
              "y":146},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd13221b5f4c467aae8f2707254c3a03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":327,
                  "y":146},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0de38f474ae44dc8ba279e8794674a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":174},
            "size":{
              "width":90,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b94ffb00b054cb58922dea64dcda410",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":174},
                "size":{
                  "width":90,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4832d615aa74e38a0a58070d94a0827",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":269,
              "y":174},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94fa30ba67d543fe973a31a74dea6c87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":269,
                  "y":174},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c34e3dadf38e4d108a03762cc338cc28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":297},
            "size":{
              "width":165,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4824c54ce4143279e6e7d6df057c910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":297},
                "size":{
                  "width":165,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcbcf23e179d4186ad33563c8c4da4f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "location":{
              "x":19,
              "y":190},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03032e3454e84129a3b6667bb8c462dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "location":{
                  "x":19,
                  "y":190},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f7d05aecd314a4b97d014a60081ff4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":700},
            "size":{
              "width":570,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf2255ea58524557bc90626d17548585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":700},
                "size":{
                  "width":570,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u24.png"}},
{
          "id":"016fc756b1c54899a4b157c935daaa8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":707},
            "size":{
              "width":244,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c16d5976e56340cf94763d795a21de8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":707},
                "size":{
                  "width":244,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54ed3b8633fb4e1196e873478984e507",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":738},
            "size":{
              "width":270,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc1b038f389144c5b8da820657882455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":738},
                "size":{
                  "width":270,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"969fbf7ba1f94ec9852badccfe6c0719",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":772},
            "size":{
              "width":507,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34df1619a6db48cd80d17ff021a629bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":772},
                "size":{
                  "width":507,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc53caf1c1cb4ab39b54138246a76626",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":159,
              "y":119},
            "size":{
              "width":46,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5992ecdf8d94c0aa1fe887e3f9e43bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":159,
                  "y":119},
                "size":{
                  "width":46,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0752a9030b941e6a39d35b203bd93bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":223,
              "y":119},
            "size":{
              "width":176,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45787031bfdb49cd8615479e80135a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":223,
                  "y":119},
                "size":{
                  "width":176,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdbd80dc8618492ca17a50e538fd355f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":159,
              "y":95},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3259b746d7d461cb298b6a0e6888c4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":159,
                  "y":95},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1141d90dbeb4c98819fbe0f29577334",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":78},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4acf9d3497f454896cb8f42ced7db45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":78},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_dashboard/u114.png"}},
{
          "id":"4c3a1701cb3d42d18d3d7d597299f02a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":340},
            "size":{
              "width":570,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d1bdbcd1123446aade9eac9d1513868",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":340},
                "size":{
                  "width":570,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u58.png"}},
{
          "id":"be929d382b004324ba26dcc8c9552111",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":910},
            "size":{
              "width":570,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cd7f022284248eaa93c9757409f47a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":910},
                "size":{
                  "width":570,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_profile/u60.png"}}]}},
  "masters":{
    "07fe86b217d14de18fc7ec21783cb4f5":{
      "packageId":"07fe86b217d14de18fc7ec21783cb4f5",
      "type":"Axure:Master",
      "name":"Menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c485460a46e745c5bdfabc2346651b2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "size":{
                "width":1100,
                "height":50},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8a06bdec040a4460953e2c3eecc03dc7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "size":{
                    "width":1100,
                    "height":50},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u130.png"}},
{
            "id":"87b90fae15cd415db6534975924189f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":51,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"05a1522716b846daa9ece22c4f685903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":51,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/employee_dashboard/u132.png"}}]}},
    "c3d56b8804094e519836cba4ec98aa37":{
      "packageId":"c3d56b8804094e519836cba4ec98aa37",
      "type":"Axure:Master",
      "name":"Employee menu",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c53b0307d0da4147910ccf3ed931a762",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":70,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Employee dashboard in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"employee_dashboard.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"8f5f1397212f454fab65667c4379d05a",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":180,
                "y":15},
              "size":{
                "width":100,
                "height":25}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Employee profile in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"employee_profile.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "1dd4ded34226424d89b58495c8cae9b5":{
      "scriptId":"u0",
      "c485460a46e745c5bdfabc2346651b2b":{
        "scriptId":"u1"},
      "8a06bdec040a4460953e2c3eecc03dc7":{
        "scriptId":"u2"},
      "87b90fae15cd415db6534975924189f4":{
        "scriptId":"u3"},
      "05a1522716b846daa9ece22c4f685903":{
        "scriptId":"u4"}},
    "faa47a1a0f8c4221b120081303e2cd2c":{
      "scriptId":"u5",
      "c53b0307d0da4147910ccf3ed931a762":{
        "scriptId":"u6"},
      "8f5f1397212f454fab65667c4379d05a":{
        "scriptId":"u7"}},
    "8ad43dcc6f6440aeb5f29dbd7964d599":{
      "scriptId":"u8"},
    "e8b1e998dfd84695a24e431e8bcb151e":{
      "scriptId":"u9"},
    "b262d1cec5b84b41b97e9dba7233082c":{
      "scriptId":"u10"},
    "30d1b642f02e44f084cb8a333866bfe5":{
      "scriptId":"u11"},
    "93517ea2c54e4f2884ca36d519f0ba08":{
      "scriptId":"u12"},
    "defc914c5cd74008af01100ff26b1927":{
      "scriptId":"u13"},
    "d08321a24f86425f998659d03949e9d7":{
      "scriptId":"u14"},
    "3c933431a8364f01b6e1f699f387e7c9":{
      "scriptId":"u15"},
    "9a60023323464f9d89929a7fb8018e4e":{
      "scriptId":"u16"},
    "303fae153dfe40dd987afbec9fc982de":{
      "scriptId":"u17"},
    "f7641296398f4876bcc69015c8d94668":{
      "scriptId":"u18"},
    "2fcfe4baf2b14ab6935ac60c66fc2416":{
      "scriptId":"u19"},
    "dd423602cfe54806b6fc5797b51ac012":{
      "scriptId":"u20"},
    "d86f7df5fd3c46338479700eaf316563":{
      "scriptId":"u21"},
    "2a5a935acf37425bbfc26c34ee87fdf0":{
      "scriptId":"u22"},
    "5835bc79141147c5ae74871f1f52687f":{
      "scriptId":"u23"},
    "620d83b0379343129d22ed9178e27533":{
      "scriptId":"u24"},
    "5b3b0cc79a2241159e51c6a2ea86ed12":{
      "scriptId":"u25"},
    "5e7779ee83424959ac3b72ed4df0910a":{
      "scriptId":"u26"},
    "134ca627495d444b9f381adaa1507560":{
      "scriptId":"u27"},
    "1f608f13663a4c8fb2395fb9ca8f3e72":{
      "scriptId":"u28"},
    "75231a2587da46248db4c710c949c813":{
      "scriptId":"u29"},
    "f573c1efc899459ba6ff3b1c2867c707":{
      "scriptId":"u30"},
    "812609d026df46daa6b87920da09134c":{
      "scriptId":"u31"},
    "503d360423b440e2a8aa9948953ca6a0":{
      "scriptId":"u32"},
    "fd13221b5f4c467aae8f2707254c3a03":{
      "scriptId":"u33"},
    "0de38f474ae44dc8ba279e8794674a31":{
      "scriptId":"u34"},
    "9b94ffb00b054cb58922dea64dcda410":{
      "scriptId":"u35"},
    "b4832d615aa74e38a0a58070d94a0827":{
      "scriptId":"u36"},
    "94fa30ba67d543fe973a31a74dea6c87":{
      "scriptId":"u37"},
    "c34e3dadf38e4d108a03762cc338cc28":{
      "scriptId":"u38"},
    "f4824c54ce4143279e6e7d6df057c910":{
      "scriptId":"u39"},
    "dcbcf23e179d4186ad33563c8c4da4f6":{
      "scriptId":"u40"},
    "03032e3454e84129a3b6667bb8c462dd":{
      "scriptId":"u41"},
    "4f7d05aecd314a4b97d014a60081ff4d":{
      "scriptId":"u42"},
    "cf2255ea58524557bc90626d17548585":{
      "scriptId":"u43"},
    "016fc756b1c54899a4b157c935daaa8d":{
      "scriptId":"u44"},
    "c16d5976e56340cf94763d795a21de8e":{
      "scriptId":"u45"},
    "54ed3b8633fb4e1196e873478984e507":{
      "scriptId":"u46"},
    "fc1b038f389144c5b8da820657882455":{
      "scriptId":"u47"},
    "969fbf7ba1f94ec9852badccfe6c0719":{
      "scriptId":"u48"},
    "34df1619a6db48cd80d17ff021a629bd":{
      "scriptId":"u49"},
    "fc53caf1c1cb4ab39b54138246a76626":{
      "scriptId":"u50"},
    "b5992ecdf8d94c0aa1fe887e3f9e43bb":{
      "scriptId":"u51"},
    "a0752a9030b941e6a39d35b203bd93bc":{
      "scriptId":"u52"},
    "45787031bfdb49cd8615479e80135a2b":{
      "scriptId":"u53"},
    "fdbd80dc8618492ca17a50e538fd355f":{
      "scriptId":"u54"},
    "b3259b746d7d461cb298b6a0e6888c4b":{
      "scriptId":"u55"},
    "f1141d90dbeb4c98819fbe0f29577334":{
      "scriptId":"u56"},
    "b4acf9d3497f454896cb8f42ced7db45":{
      "scriptId":"u57"},
    "4c3a1701cb3d42d18d3d7d597299f02a":{
      "scriptId":"u58"},
    "2d1bdbcd1123446aade9eac9d1513868":{
      "scriptId":"u59"},
    "be929d382b004324ba26dcc8c9552111":{
      "scriptId":"u60"},
    "8cd7f022284248eaa93c9757409f47a7":{
      "scriptId":"u61"}}});